### ISSUE TITLE
Adjust Individual Marks in Groups

### ISSUE THREAD

**Issue by bco71** [MarkUsProject/Markus#1009]
I suggest that having the ability to adjust individual marks within a group would make a good addition to MarkUs. This would give the professors or TAs the option to ask students to give feedback about their group members in case mark adjustments are needed. 

As far as I know, there isn't something like this yet.

**Comment by mishaschwartz** [comment]
Reasons for marking invalid:

- 7 years later and there isn't a demand for this feature
- This adds a lot of complexity for a feature that can be handled using single-membership groups/spreadsheets
