### ISSUE TITLE
Image Annotation on Mac OS X & Firefox

### ISSUE THREAD

**Issue by benjaminvialle** [MarkUsProject/Markus#125]
When using Firefox on Mac OS X and an image with annotation : if we scroll with thze two fingers on the touch pad, the annotatoin doesn't follow the scroll until we move the mouse

**Comment by david-yz-liu** [comment]
The Image annotations are only being redrawn when the mouse moves. Should be updated when the view scrolls, too.

**Comment by david-yz-liu** [comment]
@spring-ryanc This being an annotation issue is well-suited for you.

**Comment by arkon** [comment]
The annotations should move properly when scrolling in https://github.com/MarkUsProject/Markus/pull/2137
