### ISSUE TITLE
need to add seed data for completed (corrected) assignment

### ISSUE THREAD

**Issue by oneohtrix** [MarkUsProject/Markus#1419]
we should have an already completed and corrected assignment ready to use in our seeds.rb. i'm trying to fix #1418 but i would like some test data to work with so i'm working on this first.

**Comment by david-yz-liu** [comment]
@Eitredes Could you please work on this, plus put in some test data for remark requests? I've been trying to get someone to do this for months, now. :)

**Comment by Eitredes** [comment]
Can do.

**Comment by david-yz-liu** [comment]
Fixed in #2201
