### ISSUE TITLE
Assignment Submission's Table Style Not Rendering Correctly

### ISSUE THREAD

**Issue by ealonas** [MarkUsProject/Markus#1667]
The tables in Firefox are acting weird. The line to define the columns does not appear until the cursor runs over the table and disappears when you run over it again.

![screenshot from 2014-08-06 11 25 11](https://cloud.githubusercontent.com/assets/3454110/3829157/fc5c34c4-1d7d-11e4-9a63-570fcccf28ab.png)

**Comment by david-yz-liu** [comment]
Haven't been able to reproduce, and we haven't gotten any complaints about this one, so I'm closing it until we do.
