### ISSUE TITLE
Spreadsheet `marks_graders` tables are not updated after Ajax requests

### ISSUE THREAD

**Issue by zhangsu** [MarkUsProject/Markus#1673]
The current tables in the `marks_graders` view where you can assign graders to spreadsheet students (instances of `GradeEntryStudent`) are not properly updated after Ajax requests such as the "+" button for assigning graders to `GradeEntryStudent`.

It's already breaking, and it will still be broken when the React patch #1539 is merged since the Ajax requests reply on RJS to call JavaScript functions in manage_*.js, which are deleted in the React patch. But I think that's okay, as currently there aren't any proper JavaScript that handles the table updates (the current code incorrectly uses the `manage_groups.js` functions while the view doesn't have a grouping table at all!).

Is the plan to migrate to React for these tables as well?

![image](https://cloud.githubusercontent.com/assets/743034/3896310/a5f134ee-2256-11e4-96ad-65fef99c2ff1.png)

**Comment by spring-ryanc** [comment]
@david-yz-liu can you confirm that this bug still exists? I wasnt able to reproduce it... however I did notice a different issue with the buttons:
![image](https://cloud.githubusercontent.com/assets/3679565/6384928/4d7e48e4-bd31-11e4-85de-7900d45a41c3.png)

**Comment by david-yz-liu** [comment]
@spring-ryanc You're looking in the wrong spot - marks spreadsheets are different from assignments.
And yes, the bug is still happening.

Also, the buttons being fixed the middle of the page is annoying, but it's been like that for a long time now. I'm not too worried about it.
