### ISSUE TITLE
Editing 'Assignment type' doesn't always save

### ISSUE THREAD

**Issue by oneohtrix** [MarkUsProject/Markus#1674]
Editing the 'Assignment type' on an assignment is wonky in that it sometimes saves the settings and sometimes doesn't.

Repro:
1. Make an assignment, leaving 'Students can work in groups' unchecked.
2. Edit the assignment by checking 'Students can work in groups' as well as 'Automatically generate group names', then save.
3. Edit the assignment again, this time also allowing students to form groups, then save.
4. Returning to the edit assignment page, 'Students can work in groups' will be unchecked.

This is a repro that seems to work all of the time. I have encountered the same problem with other cases, though.

**Comment by david-yz-liu** [comment]
This seems to have been fixed.
