### ISSUE TITLE
Section Due Dates don't work

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#1676]
There seem to be numerous problems with these. I did some testing a few days ago and I don't think they always take effect (perhaps when they're before the global due date).

Also, I think in some places for the students, the global due date is shown/used instead of the section due date.

Just logging this issue for someone to look at more carefully later.

**Comment by david-yz-liu** [comment]
From #1702: 



If the timezone is changed from the default, two functional tests related to section due dates fail.

See #211 for more information.

**Comment by alexinman** [comment]
@david-yz-liu I'm just looking into this one now and have a couple questions. 

1) How do I change the timezone? 

2) Should the due dates be for the server time or for the users time? (At 3:00pm, I set a due date to be 2:50pm, and there was a pop up saying I was setting it in the past, which makes sense. But then afterwards it seems to be using a server time, which is an hour earlier, so the 2:50pm due date is actually being used as a 3:50pm due date.)

3) Where are all the different locations that a student can see the due date for an assignment? I've found the following locations:
 - Home page, in the Assignments Table, Due Date column
 - Assignment - Student Interface, under Assignment Rules
 - Although it doesn't actually say the due date, the submission page will say when its past the due date

**Comment by alexinman** [comment]
One problem, I've found so far with Section Due Dates:
![screen shot 2016-01-30 at 4 34 33 pm 2](https://cloud.githubusercontent.com/assets/6303087/12698303/b17ad60c-c76f-11e5-8122-680d7ed8b144.png)

**Comment by alexinman** [comment]
Another problem:
![screen shot 2016-01-30 at 4 38 36 pm](https://cloud.githubusercontent.com/assets/6303087/12698312/2c4d7c90-c770-11e5-8268-8826824fb2ee.png)

**Comment by alexinman** [comment]
Another problem:
When you submit a file after the due date the student normally gets these messages:
![screen shot 2016-01-30 at 5 01 40 pm](https://cloud.githubusercontent.com/assets/6303087/12698502/4925ae9c-c774-11e5-83be-31c896d4c85f.png)
But if the section due date has passed, but the global due date has not, they only get these messages:
![screen shot 2016-01-30 at 5 02 19 pm](https://cloud.githubusercontent.com/assets/6303087/12698507/5a6e9984-c774-11e5-811f-8f87129fa718.png)

**Comment by david-yz-liu** [comment]
@alexinman Thanks for the screenshots. Supremely helpful.

1) On Rails, try changing the time zone with http://stackoverflow.com/questions/6118779/how-to-change-default-timezone-for-active-record-in-rails
2) I don't think MarkUs does anything sophisticated with timezones - all the dates should be shown in the browser assuming the server's time zone. I thought that was what happened now, but I guess I could be wrong. The datetime picker might be doing something different, now that I think about it.
3) That's all of them, I think. Students don't have a lot of views.

**Comment by alexinman** [comment]
Just did some testing with submitting assignments before/after global/section due dates, and it seems the messages issue I was seeing above is a part of a larger issue of when students submit assignments after the section due date, but before the global due date. The files still get accepted and are able to be graded by the instructor/TA.

**Comment by alexinman** [comment]
@david-yz-liu: Currently the submissions/browse page looks like this:
![screen shot 2016-02-12 at 9 46 52 am](https://cloud.githubusercontent.com/assets/6303087/13008756/a25f806a-d16e-11e5-8ac9-170daf34062a.png)
with the 'Collect All Submissions' link at the top. Is it alright if I move it down to beside the Release/Unrelease marks? It would look something like this:
![screen shot 2016-02-12 at 9 43 16 am](https://cloud.githubusercontent.com/assets/6303087/13008769/bba2b4d4-d16e-11e5-826e-8cf6c09823ca.png)
Doing this makes it more consistent/easier for when I add a drop down when there are separate section due dates, which would look sort of like this:
![screen shot 2016-02-12 at 9 52 47 am](https://cloud.githubusercontent.com/assets/6303087/13008788/d819fce4-d16e-11e5-8987-09b11141a7df.png)

**Comment by david-yz-liu** [comment]
That's fine, but please insert a divider between that button and the Release/Unrelease buttons.

**Comment by reidka** [comment]
I like having Collect submissions as a button, but agree with @david-yz-liu that it isn't clear that the dropdown goes with the Collection button.

**Comment by david-yz-liu** [comment]
@alexinman you've made great progress, thanks a lot.

One outstanding issue I noticed: MarkUs allows some students to be assigned a section, and others not to be. This is not taken into account when doing collection. When you have time, please add an "unassigned" option to the section dropdown, which causes the submissions of the students who aren't in a section to be collected.

**Comment by alexinman** [comment]
Yes sure thing. Do you want that before or after I write the tests for section due dates?

**Comment by david-yz-liu** [comment]
After, please.

**Comment by alexinman** [comment]
This can be closed now, right?

**Comment by david-yz-liu** [comment]
@alexinman Somehow I missed this - thanks again for all your hard work last term!

**Comment by alexinman** [comment]
No problem
