### ISSUE TITLE
Change UI for "Collect all submissions"

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#1705]
We continue to see examples of instructors and TAs deleting all the marking (or all their marking) by clicking on "collect  submissions".  I'm pretty sure that there is a warning message and they have to click again, but clearly this isn't enough.

There must be something we can do within the UI to make this a less likely occurrence.  I wonder if adding a checkbox to the warning dialog would help.  For example: "I understand that clicking ok means that ALL marking for this assignments will be deleted."  It means they would have to do something different than just clicking ok.  We should also look at whether the button is in the best place or whether we need to work on rewording.

**Comment by david-yz-liu** [comment]
What if we changed the button so that if no submissions are collected, it has no dialog at all, but if at least one submission is collected, a (more prominent) dialog appears.

**Comment by DustinWehr** [comment]
How about a "delete all marking progress" (or "delete your marking progress" if user is a TA) button in addition to the "collect submissions" button, and now "collect submissions" with marking in progress tells you that you must delete marking first.

**Comment by SjoerdOptLand** [comment]
I just deleted hours of work of a precious colleague... without a warning!

It seems there is only a warning for 'Collect all submissions', but not for 'Collect work for section (drop down menu) Apply'. Could a warning please be added for that button, too?

**Comment by reidka** [comment]
It may not help much, but the data is still in the database.  We have occasionally recovered from this by using the last database backup.

We will definitely add the warning message!

**Comment by SjoerdOptLand** [comment]
Thanks for your swift reply, we’ll have a look.

Note well that with ‘Collect work from section’, I also erased work that was not attributed to me… strange, isn’t it?
