### ISSUE TITLE
"Add all code to clipboard" button in Results view

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#1810]
This is a feature request from Elizabeth, a current TA/instructor at UofT: 

Right now when a TA is grading code, if they want to copy all the code, they have to view the plain text in a new window, or download the files.

It would be nice to have a "Copy all text to clipboard" button that were only enabled for text files (but not images).

**Comment by tsimica** [comment]
JavaScript (and thus JQuery) is unable to natively copy code into the clipboard for security reasons. The workaround it to use Flash (https://github.com/zeroclipboard/zeroclipboard). 

Is this still something worth pursuing?

**Comment by tsimica** [comment]
This looks promising: https://github.com/zenorocha/clipboard.js

**Comment by zenorocha** [comment]
+1 for clipboard.js ;)
