### ISSUE TITLE
Globally set the pluralization of "criterion" to be "criteria"

### ISSUE THREAD

**Issue by kubasub** [MarkUsProject/Markus#1840]
Currently, there is an inconsistency as Rails treats the pluralization of "criterion" to be "criterions", but "criteria" is used in many places.

This change will add consistency and will simplify code such as:
`has_many :rubric_criteria, class_name: 'RubricCriterion', ...`

The pluralization can be overridden in `config/environment.rb`.

**Comment by david-yz-liu** [comment]
This has been fixed.
