### ISSUE TITLE
Current Annotations list renders raw HTML in annotation text

### ISSUE THREAD

**Issue by akbiggs** [MarkUsProject/Markus#1852]
If I enter in some raw HTML into an annotation and look at that annotation under the "Annotations" tab, the HTML is rendered by the browser as opposed to being displayed as plain text. e.g.

![screen shot 2014-10-25 at 4 57 13 pm](https://cloud.githubusercontent.com/assets/843918/4781111/0465ee3a-5c8a-11e4-8b53-48d8ceba2515.png)

![screen shot 2014-10-25 at 4 57 24 pm](https://cloud.githubusercontent.com/assets/843918/4781112/08c0aca4-5c8a-11e4-8e11-219dd3260c22.png)

**Comment by reidka** [comment]
I had an instructor complain that < > was disappearing from the annotations.  I think we need to decide whether we are going to go with plain text or render html.  If we are going to render html, then we need an obvious way in the UI to include < and >

My gut feeling is that html is not used much for annotations, and we could just drop it.
