### ISSUE TITLE
Git Branch TODO

### ISSUE THREAD

**Issue by SoftwareDev** [MarkUsProject/Markus#1855]
// Migrated from past issues

Goals:
- Figure out how to authenticate on the command line (LDAP?)
- students should be able to use git on the command line to interface with their repos
- students should have to authenticate themselves on the command line
        - Manage permissions in Gitolite like in svn

Tasks:

Completed Tasks:
- Web interface is complete.
- All tests passing as of Jan 19, 2015

Icebox:

**Comment by SoftwareDev** [comment]
@david-yz-liu I'm a little confused as to how to reproduce this. I loaded up an clean instance of MarkUs on the git branch and waited for A1 to be due and collected all submissions. Then I manually went back to the student's repo and collected one of the first submissions (with no files). After that, the collected submission for grading looked like the right one.

**Comment by david-yz-liu** [comment]
@SoftwareDev Yup, you're right. I can't reproduce the issue any more.

**Comment by reidka** [comment]
This one is really done.

**Comment by SoftwareDev** [comment]
It is amazing to see this finally completed! Great job all!

-Alex



[image: --]
Alexander Grenier
[image: https://]alexgrenier.ca
<https://about.me/alexander.grenier?promo=email_sig>
