### ISSUE TITLE
Potential Complexity Issue with finding last modified time of Git Files

### ISSUE THREAD

**Issue by SoftwareDev** [MarkUsProject/Markus#1866]
In the file git_repository.rb we implemented a method find_last_modified_date_author() which walks the commit tree and finds when a file was last modified and by whom.

This raises some complexity issues when many commits are in in a student's repo and each file requires this function to be executed. Caching may be needed if this ends up to be a real performance issue later on.

https://libgit2.github.com/libgit2/#HEAD/group/status/git_status_file looked promising but I don't think this method can be used to get author information and dates of when files are changed. @david-yz-liu 

This is a known issue with Rugged vs the actual Git commands and the performance difference between them. It would be worth looking into this if we run into issues: https://github.com/libgit2/rugged/issues/343

**Comment by adisandro** [comment]
This issue is gone with the latest git refactoring.
