### ISSUE TITLE
Intended functionality of `Assignment#past_all_due_dates?` with sections enabled

### ISSUE THREAD

**Issue by kubasub** [MarkUsProject/Markus#1926]
There are two pending RSpec test in the `Assignment` model spec that are both related to the `Assignment#past_all_due_dates?` method.

It is unclear whether or not `past_all_due_dates?` should also check the assignment's `due_date` attribute when section's are enabled.
##### Options
1. If every student does not need to be assigned to a section (with it's own `SectionDueDate`), then the method should also check the assignment's `due_date` as that is the due date those students would go by.
2. If every student needs to be assigned to a section when sections are enabled, then the method should most likely not check the assignment's `due_date` as every student will have a `SectionDueDate` to go by.

**Comment by mishaschwartz** [comment]
I think option 1 is the way to go. 
We should not have to require that all students belong to a section and the assignment due date should apply for students not in a section or for students in a section without a section due date for a given assignment.
