### ISSUE TITLE
PDF and image annotations do not work with premade annotations

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#1935]
It seems the AnnotationTextManager class for both PDFs and images registers one annotation per text, which is problematic if the same text is used in multiple annotations (this is the whole point of premade annotations).

I think this is just a rendering problem, not a database problem: all annotations should appear in the annotations list.

**Comment by wkwan** [comment]
Seems like its working. Added a bunch of a premade annotation and saw them all in the list.
![screen shot 2015-10-11 at 12 19 32 am](https://cloud.githubusercontent.com/assets/2907892/10414653/e9abc730-6fad-11e5-844e-1facb06bd07a.png)

**Comment by reidka** [comment]
They all appear in the list but not on the pdf.
