### ISSUE TITLE
Limit file size uploads

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#1938]
It would be good to have a way of limiting the size of files that students can upload.
This should also be configurable.

**Comment by MatakuT** [comment]
I took it over

**Comment by david-yz-liu** [comment]
Made progress on this issue in ffdc390349ec924628b552dbc8a50c93f94f26fc.

Some things to think/talk about:
- [ ] Make the size limit configurable in config/{development, test, production}.rb
- [ ] Customize size limit based on file type (e.g., images are bigger?)
- [ ] Allow customization in Assignment settings interface. E.g., "Enable file size limit (5 MB)"

**Comment by MatakuT** [comment]
1. never actually worked with those files directly, so not sure how to go about it. Would this mean creating options like 500kb, 5mb, 10mb, etc?
2. It might or might not be useful. Images on their own should not be bigger than 5-6 mb, unless it's a photography class where they might require hight definition images. The size flexibility might come in handy with video submissions, but I think Markus does not deal with those. The ideal solution to me seems to restrict .doc/.pdf/.txt(....) to 1 mb and allow images/binary to be up to 5. Do 5mb max and prompt a user to compress the file and re-submit. 
3. I think allowing teachers to choose the file size limits would create more work for them. Now they have to think beforehand about all the cases of student`s submissions and look whether there is a chance of getting bigger files. If I were a teacher I would want to play safe and leave this checkbox unchecked just in case of some exceptions.

**Comment by DustinWehr** [comment]
I have students who've submitted PDFs big enough that they cause the site to become unresponsive. It would be nice to be warned of this, so I don't have to keep killing the tab process. 
perhaps if it's over 8 MB, you require clicking a button before the file loads in viewer? then i could still grade it by downloading the PDF.

**Comment by MatakuT** [comment]
What kind of warning message do you see associated with that button?

**Comment by reidka** [comment]
If it is easy (fast) to determine the size of the file, then the message could be something like:

Warning, file is XX MB.  Loading it in the web viewer may take a long time.
<continue>  <dowload file instead>

**Comment by DustinWehr** [comment]
Yep that would be a good warning message. You could also recommend using another browser if they are using Chrome. Firefox works for me, even for large PDFs.

**Comment by MatakuT** [comment]
made a progress on this issue: #2084

**Comment by DustinWehr** [comment]
@MatakuT thanks! 
I've since learned that the problem I mentioned above with Chrome might not be due to file size alone. The PDFs that crashed markus for our assignment had sizes: 126KB, 1MB, 1.5MB, 3.8MB, 4MB, 5.1MB, 6.4MB, 7.7MB, 8.2MB.

**Comment by david-yz-liu** [comment]
@DustinWehr I wonder is somehow those PDFs are not cooperating with MarkUs. Could you please send them to me?

**Comment by reidka** [comment]
I think the message is fine, and we should go ahead with it, but I'm not sure whether it is solving a real problem.  Is there a way to detect if pdf.js is having trouble opening the file and using the same message for that?

**Comment by MatakuT** [comment]
I will take a look at pdf.js
Unfortunately, there is no way for me to properly test javascript functionality due to problems with configuring Selenium for the vagrant box. But I'll see if I can tell anything from looking at the code.

**Comment by MatakuT** [comment]
The problem is not in uploading the file to the server, but the browser freezing while trying to open/render pdf file. As I said above, there is no way to properly test in all browsers. This issue has nothing to do with limiting the file size while uploading the files. As @DustinWehr mentioned, this happens with all kinds of file sizes. I think there should be a separate ticket describing the problem, the browser and the troublesome pdf(s) attached for de-bugging. This issue has nothing to do with MarkUs component, but rather with external code. Upgrading PDFJS or browser that is used to open pdf(s) may resolve the issue.

**Comment by reidka** [comment]
This is a thornier issue that I realized.  Students are frequently trying to upload pdfs in the 10 MB range.  I have seen one report of a "Bad Gateway" message.  It would d be nice to have the warning message saying the file is too big.

It is also increasingly important to get a sense of why uploading large files is a problem.
