### ISSUE TITLE
Rename "Grade Entry Form" to "Marks Spreadsheet" in Properties page

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#1967]
When creating/updated a spreadsheet, the button is labeled "Create [Update] Grade Entry Form"; this should be changed to "Create [Update] Marks Spreadsheet".

**Comment by spring-ryanc** [comment]
Hi David, I have a working fix for this bug. I just want to confirm that I'm following standards before commiting the changes. Perhaps we could briefly discuss it in the next webchat?

I added the text to the en.yml file and added the following to the form: t(f.object.new_record? ? 'grade_entry_forms.create.submit' : 'grade_entry_forms.edit.submit')

**Comment by reidka** [comment]
Done.
