### ISSUE TITLE
Is the MarkUs logo in the navigation bar slightly too low?

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#1968]
I'm not sure if the logo gets cropped at the bottom or not, or if it's just my machine. @arkon?

**Comment by arkon** [comment]
It could be a browser issue. Can I see a screenshot too?
On Jan 8, 2015 1:08 PM, David Liu <notifications@github.com> wrote:I'm not sure if the logo gets cropped at the bottom or not, or if it's just my machine. @arkon?

**Comment by david-yz-liu** [comment]
![nav](https://cloud.githubusercontent.com/assets/3333115/5669608/e854999c-9746-11e4-8d36-b9442efb68ab.png)

**Comment by arkon** [comment]
@david-yz-liu Hmm I think it looks a little bit cropped in Chrome for me too. I'll try to fix it up soon.
