### ISSUE TITLE
Grace period preview times don't match due date

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#1971]
When creating a new assignment:

1. Set a due date.
2. Choose the grace period submission rule
3. Enter any number of hours, and then change focus (e.g., click "add another period")

The previewed grace period times don't match the due date. I have a feeling this is a time zone issue.

**Comment by arkon** [comment]
It does in fact seem to be a time zone issue, since it's 5 hours off (GMT vs. EST). I thought I squashed these issues but I guess not. :(

**Comment by reidka** [comment]
Just tested this and it seem to work now.
