### ISSUE TITLE
Add "Bonus" columns to spreadsheets

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#1974]
Right now every column in a spreadsheet contributes to the total mark (and thus the average calculation).

It would be nice (e.g., for bonus questions on exams) to mark a column as "bonus".

**Comment by peterzhao333** [comment]
@david-yz-liu Could you elaborate on the behaviour for bonus columns when it comes to the total mark, and computing class average calculations?

Are marks in bonus columns supposed to be added to the student's total mark? (If not, I was wondering how would the student know their final mark with bonus marks included? )

Are marks in bonus columns supposed to be added to class average calculations?

**Comment by david-yz-liu** [comment]
They can be added to the total mark, and hence average calculations. The main point is the point value for the column shouldn't be added to the point total for the whole spreadsheet.

**Comment by peterzhao333** [comment]
When you say point value of the column, and point value for the whole spreadsheet, are you referring to the Grade/Admin view of the Editable Spreadsheet?

**Comment by david-yz-liu** [comment]
Yes, but this (should) also be what's used to calculate averages, which the students see.

**Comment by peterzhao333** [comment]
@david-yz-liu I updated the pull request with the change. Let me know if this was what you meant.
