### ISSUE TITLE
In assignments table, add column header for "submissions" column

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#1977]
In the main assignments view, the third column should have a header like "Submission Status".

**Comment by jiangha4** [comment]
I'll take a look!

**Comment by jiangha4** [comment]
Hey David I think I got a fix in for this. I just google translated Submission Status into French and portuguese so I'm not quite sure if it's grammatically correct or not.

**Comment by david-yz-liu** [comment]
@jiangha4 Great! I'm okay with Google translate, we've been a bit loose with recent translations and will need to take a hard look at the overall translations soon enough.
