### ISSUE TITLE
Rails 4: Collect all submissions is broken

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#1996]
ActiveRecord::StatementInvalid in SubmissionsController#collect_all_submissions
PG::InvalidTextRepresentation: ERROR: invalid input syntax for integer: "--- :include: - :groupings " LINE 1: ...".* FROM "assignments" WHERE "assignments"."id" IN (1, '--- ^ : SELECT "assignments".* FROM "assignments" WHERE "assignments"."id" IN (1, '--- :include: - :groupings ') ORDER BY due_date ASC

Extracted source (around line #186):
  def collect_all_submissions
    assignment = Assignment.find(params[:assignment_id], include: [:groupings])
    if assignment.submission_rule.can_collect_now?
      submission_collector = SubmissionCollector.instance
      submission_collector.push_groupings_to_queue(assignment.groupings)

**Comment by tsimica** [comment]
This issue should be closed?

**Comment by david-yz-liu** [comment]
Thanks, @tsimica
