### ISSUE TITLE
PDF encoding issues prevent rendering

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#2011]
I uploaded a PDF that apparently had some formatting or encoding issues, as this was the result:

![pdfs](https://cloud.githubusercontent.com/assets/3333115/5821839/18029748-a09d-11e4-81ea-b4147fa2818a.png)

Karen says that in the old collection process, PDFs were run through some sort of linter before being coverted to images. It may be worth doing the same now as PDFs are stored.

Contact me for the PDF.

**Comment by tsimica** [comment]
@david-yz-liu Please e-mail me the submissions.

**Comment by wkwan** [comment]
Is this still an issue?
