### ISSUE TITLE
SubmissionRule's children need order

### ISSUE THREAD

**Issue by tsimica** [MarkUsProject/Markus#2028]
Coupled with issue #1738, there is no way of knowing which SubmissionRule takes precedence over the other. This means that enumerating all of the SubmissionRules (in practical terms, listing the penalties being late) for a particular assignment will be guaranteed to be in the correct order.

**Comment by mishaschwartz** [comment]
This has been implemented for penalty periods and penalty decay formula.

Requires update to list order of grace period deductions. Possible messages:

- a grace credit will be deducted 2 hours after the deadline (`deadline + 2.hours` time stamp)
- a grace credit will be deducted 4 hours after the deadline (`deadline + 4.hours` time stamp)
- etc.
