### ISSUE TITLE
Error when reorder marking scheme criteria

### ISSUE THREAD

**Issue by DustinWehr** [MarkUsProject/Markus#2030]
As a result, I can't change the order of the criteria. Errror dump from Chrome's console below. Source code reference column should be shifted down by 1.

Uncaught ReferenceError: ajaxRequest is not defined   
       rubrics:44
jQuery.sortable.update   application.js:16399 
e.Widget._trigger   application.js:16399 
e.widget._trigger   application.js:16399 
(anonymous function)   application.js:16399 
(anonymous function)   application.js:16399
e.widget._clear   application.js:16399 
(anonymous function)   application.js:16399 
e.widget._mouseStop   application.js:16399 
(anonymous function)   application.js:16399 
e.widget._mouseUp   application.js:16399 
(anonymous function)   application.js:16399 n._mouseCapture._mouseDistanceMet._mouseDelayMet._mouseUpDelegate   application.js:10725 jQuery.event.dispatch   application.js:10393 
elemData.handle

**Comment by reidka** [comment]
Also, the order doesn't stick.  On refreshing the page it goes back to the original order.

**Comment by DustinWehr** [comment]
Thanks @david-yz-liu !
