### ISSUE TITLE
Session expiry isn't obvious to the user

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2037]
I have seen lots of comments from TAs like the following:

Also, when my session expires, I don't get logged out, so it's not until I
do something and nothing happens that I realise that my session expires,
which is a bit annoying if I've just typed in a long comment! (This is not
what happens in the previous case, which can happen immediately after I've
logged in.)

Could we pop up an "expired session" modal on the client side after some period of inactivity?

**Comment by Eitredes** [comment]
working on this
