### ISSUE TITLE
Time left to submit needs more work..

### ISSUE THREAD

**Issue by priyank-purohit** [MarkUsProject/Markus#2041]
Self explanatory.
![time-left-is-wrong](https://cloud.githubusercontent.com/assets/8868691/6197862/a633fb20-b3bb-11e4-8c9e-477dad41551a.png)

**Comment by arkon** [comment]
That's correct, it's just missing the "58 minutes" part.

**Comment by lifejuggler** [comment]
why would the system need to show 0 days as well, would it not be better to just show 1 hour left or 58 minutes left? Maybe also turn the letters red when its under an hour would help students know that its really close to deadline

**Comment by tsimica** [comment]
Working on this.

**Comment by tsimica** [comment]
Also mentioned during the meeting this week:
- Add 1 minute when checking the submissions so that when an assignment is due at 10:00pm and a user submits at 10:00:05pm, consider as "on time".
