### ISSUE TITLE
Multli-line annotations for text files need page refresh to display correctly

### ISSUE THREAD

**Issue by paymog** [MarkUsProject/Markus#2045]
Steps to repro:
1) Start marking an assignment with a text file
2) Select some text and create a new annotation with the following content (select an annotation category other than 1 time)
<pre>
here is some content

I've added some new lines

it seems that new lines break things

not quite sure what yet. I'm also ensuring that this gets truncated in the annotation list.
</pre> 
3) Create the annotation
4) Notice that the selected lines do not get highlighted
5) Refresh the page
6) The lines are now highlighted and the annotation is working correctly

Additionally, this also occurs when the multiline annotation is selected from the predefined list (the reason the steps above suggest selecting an annotation category).

**Comment by paymog** [comment]
I think I've figured it out. Should be fixed upon mathjax integration.

**Comment by david-yz-liu** [comment]
Seems fixed now.
