### ISSUE TITLE
Loses annotations MAJOR bug

### ISSUE THREAD

**Issue by DustinWehr** [MarkUsProject/Markus#2063]
Reported to me by Alex lex@cs.toronto.edu. Contact him for details.

**Comment by arkon** [comment]
Do you mean alex@cs.toronto.edu ?

**Comment by david-yz-liu** [comment]
@DustinWehr Tell your TA to email us.

**Comment by DustinWehr** [comment]
No, I meant lex@cs.toronto.edu

**Comment by DustinWehr** [comment]
I'm not going to tell Alex to do anything because I only barely cared enough to file this bug in the first place. MarkUs might be the buggiest program I have ever used.

**Comment by DustinWehr** [comment]
I am having to do some grading now. I notice that sometimes my new annotation *appears* to be lost, but after I refresh the page the page it shows up. Perhaps that was the issue? I'm sending him the link to this page.

**Comment by david-yz-liu** [comment]
Okay - are you annotating PDFs when this happens?

**Comment by DustinWehr** [comment]
Yes. Unfortunately I don't know how to reliably reproduce it.
