### ISSUE TITLE
Ids in the footer are repeated

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#2068]
Once in the footer below the content div (full size), once in the footer in the nav (mobile breakpoint). W3C complains about the duplicate ids.

@arkon what's the best way to resolve this?

**Comment by arkon** [comment]
I guess to use classes instead.

**Comment by david-yz-liu** [comment]
Yeah, I guess. You originally put the footer in the nav bar - do you not think it looks good at the bottom for mobile?

**Comment by arkon** [comment]
I was trying to reduce the amount of clutter when on mobile, so most of the stuff got stuffed into the nav drawer. I'll probably revisit it at some point and pull some stuff back out, like the submenus, along with just restyling the regular footer instead of putting it in the drawer like it is now.

**Comment by arkon** [comment]
@david-yz-liu Can be closed via https://github.com/MarkUsProject/Markus/pull/2080

**Comment by david-yz-liu** [comment]
Thanks @arkon
