### ISSUE TITLE
Add note for student fails 

### ISSUE THREAD

**Issue by DustinWehr** [MarkUsProject/Markus#2070]
Console:
Failed to load resource: the server responded with a status of 404 (Not Found)  https://markus.cdf.toronto.edu/en/notes/noteable_object_selector

Reproduce:
Notes tab --> Add a new note --> Select "student" or "assignment" in the Noteable dropdown.

**Comment by lifejuggler** [comment]
this is currently not reproducible in development environment. Perhaps the selected student or assignment does not exist?

**Comment by david-yz-liu** [comment]
Got it, it's a problem with relative directories. @DustinWehr, would you like us to fix this for this term?

**Comment by david-yz-liu** [comment]
Okay, well it's fixed now, I believe. Please let me know if there are other problems.

**Comment by DustinWehr** [comment]
Great thanks! Sorry I didn't reply. My email notification address was set to an old internship address.
