### ISSUE TITLE
parse_csv action crashes in grade_entry_form controller

### ISSUE THREAD

**Issue by MatakuT** [MarkUsProject/Markus#2075]
upload_csv should gracefully fail on non-csv file with .csv extension, but right now it throws an exception. upload_csv only checks for correct file extension and passes the file to parse_csv which cannot candle non-csv files. 

Edit: Here is the error that I'm getting
     CSV::MalformedCSVError:
       Illegal quoting in line 2.

**Comment by david-yz-liu** [comment]
Thanks, @MatakuT. @paymog this is basically the same error as before.

**Comment by paymog** [comment]
Sounds good. Wanna assign it to me?

**Comment by paymog** [comment]
I've fixed this problem but one of the tests is now failing. Specifically, a test in ```grade_entry_forms_controller_test.rb``` which ```should 'have invalid values in database after an upload of an ISO-8859-1 encoded file parsed as UTF-8'```

I must be misunderstanding something because it seems that the test is expecting to DB to have invalid values when the user messes up. Surely this isn't what's actually desired.

**Comment by david-yz-liu** [comment]
Yes, you can remove the test.
