### ISSUE TITLE
parse_csv action crashes in grade_entry_form controller for a different file

### ISSUE THREAD

**Issue by MatakuT** [MarkUsProject/Markus#2078]
I wrote a test to parse a csv file which only has value '5' in cell A1 (if you try opening through excel app).
This test should gracefully fail saying that the given column names do not match the required column names. Right now it fails with the following error:
 EOFError:
       end of file reached

**Comment by MatakuT** [comment]
Update: I discovered that it has nothing to do with invalid column names, but rather with the fact that the first cell A1 must be empty, but contains value of '5'.
Still, this has to be handled properly.

**Comment by MatakuT** [comment]
@david-yz-liu, this one definitely has to be fixed.
Should a user get an error message saying that new line has to be appended to the end of the file?

**Comment by david-yz-liu** [comment]
I mean, it would be better if a newline were not required at the end of a file. Do you think that's a feasible thing to do?

**Comment by MatakuT** [comment]
The terminal newline is required as some programs/commands (mostly UNIX-based) do the parsing assuming that the last line is either '/n' or '\r\n'.
I can throw an exception catching the absence of end of file newline and try appending it and re-uploading the file. I will have to look into this a little bit more

**Comment by MatakuT** [comment]
Another problem with end of file terminators.
The upload function seems to be having troubles with Windows newlines ('\r\n')
It tolerates "ASCII text", but does not allow "ASCII text, with CR, LF line terminators".
MarkUs throws the malformed_csv error message: "The selected file was improperly formed. Please ensure the file meets Markus specifications." which is correct, but does not provide enough information to resolve the issue. 
I will try to catch '\r\n' along with no newline and replace with a proper '/n'

**Comment by MatakuT** [comment]
made a progress: #2111
