### ISSUE TITLE
Repository Folder no longer auto-populates with short identifier

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#2087]
I just noticed this recently, should be an easy fix. Don't think anyone was working on this part of the code much.

**Comment by Eitredes** [comment]
I'm not quite sure what this issue is. Can you describe it in more detail, please?

**Comment by david-yz-liu** [comment]
It used to be that when a user entered text into the "short identifier" field, on every keyup the "repository folder" field updated to contain the exact same text.
