### ISSUE TITLE
Simple Grade Spreadsheet: uploaded file overrides column name

### ISSUE THREAD

**Issue by MatakuT** [MarkUsProject/Markus#2101]
When I try uploading a new csv file with a wrong column name - it overrides the template with correct column name.
Meaning, if the initial column name at B1 is "Name 1" I can freely upload the file which has a value "Name 2" in B1. "Name 2" will replace "Name 1".
This behaviour should be restricted.

**Comment by MatakuT** [comment]
@david-yz-liu, please assign this to me

**Comment by david-yz-liu** [comment]
Same as #2102, not a problem.
