### ISSUE TITLE
Simple Grade Spreadsheet: uploaded file appends extra columns

### ISSUE THREAD

**Issue by MatakuT** [MarkUsProject/Markus#2102]
When I try uploading a new csv file with an extra column - it overrides the template appending this new column.
Meaning, if the only column is at B1  I can freely upload the file which has another column in C1. The template will adopt this new column
This behaviour is ambiguous and seems undesirable. I would like to restrict adding extra columns to Simple Grade Spreadsheet by simply uploading the file. Extra columns should be added only in the edit view.
If you think that adding extra columns via file upload should be allowed, please justify.

**Comment by MatakuT** [comment]
@david-yz-liu, please assign this to me

**Comment by david-yz-liu** [comment]
Some people like using Excel to store their marks, and only upload them to MarkUs to display marks to students. Adding new columns at upload time is fine.
