### ISSUE TITLE
Simple Grade Spreadsheet: uploaded file overrides grade total

### ISSUE THREAD

**Issue by MatakuT** [MarkUsProject/Markus#2103]
When I try uploading a new csv file with a wrong grade total - it overrides the template with correct grade total.
Meaning, if the initial total at B2 is "100" I can freely upload the file which has a value "20" in B2. "20" will replace "100".
One potential danger is that the marks inputted will be out of 100, but the new total is 20. Marks such as 86 out of 20 would not make sense. 
This behaviour should be restricted.

**Comment by MatakuT** [comment]
@david-yz-liu, please assign this to me.

As a side fix, there should be a check for the marks inputted to be less than or equal to total and vice versa - new total should be always greater than or equal to the marks already in the sheet.
If a user tries to change the total with the marks being in the csv - such user should get a warning message stating that all marks have to we wiped out before proceeding. Not sure if there should be a separate ticket for this or it can me implemented as a part of this ticket.

**Comment by david-yz-liu** [comment]
Same as #2102. People can change the grade totals via uploading. I don't see a problem with allowing a grade awarded to be greater than the mark allocation for a column (e.g., bonus marks).
