### ISSUE TITLE
Submissions view shows all members (including those that haven't accepted)

### ISSUE THREAD

**Issue by tsimica** [MarkUsProject/Markus#2109]
When looking at a group in the grades view, it will show the current members of the group. However when looking at the Submissions view, it will show the members that have been invited but not accepted the invite.

Note: This bug needs to be verified.

**Comment by wkwan** [comment]
If by "grades view" we mean the tab that says "Groups", yes I see all the members of the group including the not accepted ones. I'll fix this.

Example with c5granad inviting c6janace but c6janance not accepting:

![image](https://cloud.githubusercontent.com/assets/2907892/10101688/305a537e-6368-11e5-9945-658d8d28349d.png)

![image](https://cloud.githubusercontent.com/assets/2907892/10101719/5aefc754-6368-11e5-89e1-f876c02b4219.png)

**Comment by reidka** [comment]
It would be good to include invited students in the groups table, but style differently (append an asterisk?) to those that are invited but have not accepted.
