### ISSUE TITLE
Add a warning message for overriding column names/grade totals on csv file upload 

### ISSUE THREAD

**Issue by MatakuT** [MarkUsProject/Markus#2112]
There is a possibility of accidentally overriding column names/grade totals via uploading csv file. A warning message should be added to confirm if a user actually wishes to override an existing template.

**Comment by MatakuT** [comment]
made some progress: #2115

**Comment by mishaschwartz** [comment]
Reason for marking invalid:

- when uploading a csv file there is now a checkbox to choose whether to overwrite existing marks or not.
