### ISSUE TITLE
MAJOR bug: "Add Extra Mark" in remark request does nothing

### ISSUE THREAD

**Issue by DustinWehr** [MarkUsProject/Markus#2135]
This has left me unable to close a student's remark request. They got extra points before for leaving a question blank, and now I can't assign those points.

**Comment by DustinWehr** [comment]
Work-around: 
As long as you don't ever hover over "Show Old Mark Summary" (if you do, you'll have to reload the page and try again), you can see both the old and new marks in "Summary" tab.
When you click "Add Extra Mark" in the second, new marks section, it'll inset a form in the first, old marks section. Adding the extra marks appears to add them to the new marking.

**Comment by david-yz-liu** [comment]
This has been fixed for next year.
