### ISSUE TITLE
Student file manager issues

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#2155]
@arkon has nicely pointed out stylistic issues in the new student file manager:
- [x] Column with checkboxes should be hidden if the assignment disallows web submits
- [x] Filenames should link to the files (like the old file manager)
- [x] Last revised datetimes should be nicely formatted (this is a simple internationalization fix)
- [x] Searchbox could use some placeholder text
- [x] File table doesn't appear when web submits are not allowed.

**Comment by arkon** [comment]
> Filenames should link to the files (like the old file manager)

Somebody just brought this up to me again today. Seems like it would be a nice feature to bring back.

**Comment by arkon** [comment]
I think the last item ("File table doesn't appear when web submits are not allowed.") is okay now.

**Comment by david-yz-liu** [comment]
Yes, thanks for the reminder.
