### ISSUE TITLE
Date picker: allow inputting dates in any format

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#2158]
Dan Zingaro reports that in the current date picker (e.g., in Assignment -> Settings), he must type in the full localized string "Wednesday, May 13 2014", where before he could type in "2014/05/13". 

Seems like a simple fix... @arkon? :D

**Comment by arkon** [comment]
Bizarre, shouldn't it just show the date picker instead?

**Comment by david-yz-liu** [comment]
He needs to be able to type in dates, seems like the picker doesn't interact well with his software. I should add that he *was* able to type in manually the long version.

**Comment by david-yz-liu** [comment]
Resolved in #2186.
