### ISSUE TITLE
Vagrant linux image requires cmake for git branch

### ISSUE THREAD

**Issue by SoftwareDev** [MarkUsProject/Markus#2161]
In order to run `bundle install` successfully on the git branch, the Vagrant linux image (or any linux install) requires that the cmake library is installed or otherwise the rugged 0.21.4 gem will fail to install.

Perhaps add this library to the markusproject/ubuntu image or just add to the instructions that cmake is required separately... by simply running `sudo apt-get install cmake`?

**Comment by david-yz-liu** [comment]
@oneohtrix Can you please add cmake to the image?

**Comment by SoftwareDev** [comment]
@oneohtrix @david-yz-liu It's also going to require gitolite.
`sudo apt-get install gitolite` should get the files required if one chooses to use Git functionality later on. The package will install but won't get setup unless the user chooses to run `sudo dpkg-reconfigure gitolite` after.. but I'll provide instructions on that somewhere on the Wiki.

**Comment by SoftwareDev** [comment]
@oneohtrix Sorry couple more dependencies: `sudo apt-get install libssh2-1 libssh2-1-dev libgpg-error-dev`

**Comment by oneohtrix** [comment]
Oh crap, sorry I didn't see this! I'll add it ASAP.

**Comment by SoftwareDev** [comment]
@oneohtrix Its actually okay! I edited the Vagrant instructions to account for this.

**Comment by david-yz-liu** [comment]
Well if @oneohtrix adds it to the image, that's better in the long run since it removes an installation step.

**Comment by SoftwareDev** [comment]
@oneohtrix @david-yz-liu Okay, Lawrence if you look at this wiki page https://github.com/MarkUsProject/Wiki/blob/master/SettingUpVagrantEnvironment.md (not sure why its not on the main MarkUs wiki yet) you can see the additional setup I had to do to get Gitolite working.

**Comment by oneohtrix** [comment]
hey @david-yz-liu @SoftwareDev -- can this be closed?

**Comment by david-yz-liu** [comment]
Yes, thanks.
