### ISSUE TITLE
download all submissions button broken?

### ISSUE THREAD

**Issue by jmzaleski** [MarkUsProject/Markus#2169]
I have an assignment that is past due. I choose the assignment, then the submissions tab, and click the "Download all submissions" link in the upper right. (See screenshot)

I get a 22 byte empty zip file. Is this not a bug?

![image](https://cloud.githubusercontent.com/assets/9355220/7773578/7882b2e8-0073-11e5-8eff-de69e477ad72.png)

**Comment by david-yz-liu** [comment]
Hi @jmzaleski, I believe you need to "Collect all submissions" first (this determines which version of the files students submitted to use). Please try that, and then try downloading all the submissions again.
