### ISSUE TITLE
Users can log in even with wrong password

### ISSUE THREAD

**Issue by senshu** [MarkUsProject/Markus#2179]
Using MarkUs 1.0-rc1

Steps to reproduce :
1. As administrator, create a user account X and log out.
2. Log in as X with a password P, then log out.
3. Attempt to log in as X with another password.

Observed result : the second attempt to log in is successful, even with the wrong password.
Expected result : the second attempt to log in should fail.

**Comment by david-yz-liu** [comment]
Hey @senshu,

MarkUs doesn't check passwords by itself, but instead sends login information to a script - the default validator provided accepts any non-empty password (`config/dummy_validate.sh`). You can change this by setting the `VALIDATE_FILE` variable in the config/environment files.

**Comment by senshu** [comment]
> MarkUs doesn't check passwords by itself, but instead sends login information to a script

I have finally found this information by myself. I don't understand why there is no clear mention of this in the installation guide. A comment inside a config file does not seem like an appropriate place to document a critical feature.

> the default validator provided accepts any non-empty password

For security reasons, I think that the default validator should *reject* all passwords. This would force the admin to act.

> You can change this by setting the VALIDATE_FILE variable in the config/environment files.

Should I write my own validator or is there a working solution that I could use?
