### ISSUE TITLE
Creating groups for assignments where students work alone

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2180]
When students work alone, we want their repo name to be the same as their user id.  When students log into MarkUs and navigates to the particular assignment the repo is created or assignment folder added to existing repo.  

The cases where this doesn't work well are:
1. The instructor wants to add starter code to the student repos.  The "groups" must be created for the instructor to do this.  The possible workaround of using a CSV upload to create the groups fails because the CSV upload is currently ignoring the repo column and auto generating repos.

2. We want to add a new group in the web view manually.  It will auto-generate a repo name even if we want to just add a new student.

The requested fix for these case is to add a button to the Groups tab when the assignment is intended for working alone.  The button will create the repos that don't exist and add folders for the assignment where they do not exist.  The button will not affect groups that are already set up.

(I wonder if this will also fix the problems of groups suddenly appearing in the submissions table uncollected much later.  I couldn't find an issue for this.)

We have a similar problem with CSV uploads and groups that allow 1-N members.  I don't think this is a common use case.

**Comment by reidka** [comment]
This is pretty high priority

**Comment by david-yz-liu** [comment]
Completed in #2297
