### ISSUE TITLE
Course Summaries download CSV

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#2203]
We need to move the "Download all assignment data" functionality from the assignments list to the course summaries page.

Also, we need to add both *spreadsheet total marks* and *marking scheme weights* to the downloaded CSV.

@dannyreis @PatGuan

**Comment by PatGuan** [comment]
Hey David,

Sorry but for the spreadsheet total marks column, did you want the total marks for A1-A4 summed up as they are on the CSV or did you want them summed up but with their corresponding weights? I'm guessing the latter?

**Comment by david-yz-liu** [comment]
Yeah, definitely the latter.

**Comment by david-yz-liu** [comment]
Fixed in #2216.
