### ISSUE TITLE
Styling for dashboard is off if there are no assignments

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2227]
I have tried it on Chrome and Safari, and it looks the same.  

The Marks spreadsheets section overlaps with the footer.

<img width="1163" alt="dashboard" src="https://cloud.githubusercontent.com/assets/420794/9685321/88d4654a-52eb-11e5-9d52-afefb01f495a.png">

**Comment by arkon** [comment]
Weird, something must be `float`ing, even though there's no reason for it to.

**Comment by melneubert** [comment]
Working on this one.
