### ISSUE TITLE
Styling problem for creating a new assignment

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2230]
On Firefox, when I went to create a new assignment, here is what I saw.  The Repository Folder should be on the next line.
<img width="1008" alt="styling_problem" src="https://cloud.githubusercontent.com/assets/420794/9950548/c50513ae-5d89-11e5-95f9-4961ea22f875.png">

**Comment by reidka** [comment]
low priority.  I realized this happened because I had increased font size on my browser.

However, it would be nice if the label wrapped with the text box.

**Comment by WilsonChiang** [comment]
Taking this

**Comment by WilsonChiang** [comment]
PR open https://github.com/MarkUsProject/Markus/pull/2241
