### ISSUE TITLE
CSV Group upload is still not working well

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2237]
Related to #1766, #1822 
Also related to #2180 
We thought this was fixed in https://github.com/MarkUsProject/Markus/commit/1183682d8d96e47208f48387b488638b966a8c93

On our production test server (with 1500 students). 
1. I was able to upload 400 groups with 1 member per group
2. I was not able to upload 600 groups  (proxy error 502)
3. We need to be able to upload groups incrementally.  This will have to be done carefully so that a student is not a member of two groups.
4. We really need to be able to figure out what is causing the 502 error.

**Comment by david-yz-liu** [comment]
Fixed in #3823.
