### ISSUE TITLE
Assignment not collected causing errors on remark request

### ISSUE THREAD

**Issue by wkwan** [MarkUsProject/Markus#2252]
When no submissions are made until after the assignment deadline and the assignment is marked using "Collect All", no files appear when marking but the assignment can be graded. This also causes this error when the submitter puts a remark request for that assignment.

Started POST "/en/assignments/8/submissions/1/results/8/codeviewer" for 10.0.2.2 at 2015-09-18 18:56:20 -0400
Processing by ResultsController#codeviewer as */*
  Parameters: {"submission_file_id"=>"", "focus_line"=>"undefined", "authenticity_token"=>"GT6myZ6wqmgZfuNUrMCaC0kkp3iXx0dADzdZE5vP1GS61atNIRJJFFrA2d487QLDy51F318MeQ9ebV/RUaMWWA==", "locale"=>"en", "assignment_id"=>"8", "submission_id"=>"1", "id"=>"8"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 21]]
  Assignment Load (0.2ms)  SELECT  "assignments".* FROM "assignments" WHERE "assignments"."id" = $1  ORDER BY due_date ASC LIMIT 1  [["id", 8]]
  SubmissionFile Load (0.2ms)  SELECT  "submission_files".* FROM "submission_files" WHERE "submission_files"."id" = $1 LIMIT 1  [["id", nil]]
Completed 404 Not Found in 7ms (ActiveRecord: 0.6ms)

ActiveRecord::RecordNotFound (Couldn't find SubmissionFile with 'id'=):
  app/controllers/results_controller.rb:309:in `codeviewer'

**Comment by wkwan** [comment]
Also, when this situation occurs, if the admin selects the "Repository" for this empty submission, will get: 

Showing /home/vagrant/Markus/app/views/submissions/repo_browser.html.erb where line #69 raised:

undefined method `[]' for nil:NilClass

**Comment by reidka** [comment]
I can't replicate this.
