### ISSUE TITLE
Refactor layout for assignment scoped views

### ISSUE THREAD

**Issue by jeremygoh** [MarkUsProject/Markus#2268]
There are a lot of common elements in the views for `assignments/:id/...`

We should refactor and extract common elements for the assignments scoped url into their own layout
Specifically
- [ ] Settings
- [ ] Groups
- [ ] Graders
- [ ] Tags
- [x] Submissions (browse)
- [ ] Summaries

Later on, we may want to consider using this layout consistently for other more generally scoped views like `/students`

**Comment by jeremygoh** [comment]
I'm currently looking at this

**Comment by jeremygoh** [comment]
When logged in as a student, the file manager is rendered without a layout. I'll put up a fix for this shortly.

**Comment by david-yz-liu** [comment]
@b2simms note: the comment from last year no longer applies, so you should be working just on using the new `assignment_content` layout.

**Comment by mishaschwartz** [comment]
Reason for marking as invalid:

- the work was done but this issue was not closed
