### ISSUE TITLE
Confirmation for group member disinvite does not work

### ISSUE THREAD

**Issue by WilsonChiang** [MarkUsProject/Markus#2272]
Currently, there is code in place for confirming that you want to disinvite a group member in `assignments/_member.html.erb`:

```
     <%= link_to I18n.t(:cancel), '#',
        onclick: "
          new Ajax.Request('" +
             disinvite_member_assignment_path(id: @assignment.id, membership: member.id) + "');",

        confirm: I18n.t("student.cancel_invitation"),
        title: I18n.t("student.cancel_invitation_title"),
        class: "delete",
        remote: true
        %>
```
However, the confirmation window never happens.

**Comment by WilsonChiang** [comment]
Looks like this is related to having both jQuery and Prototype.

See: http://stackoverflow.com/a/4988142

**Comment by WilsonChiang** [comment]
Looks like the flash message that is apart of this does not load either in `assignments_controllers.rb`:

```
flash[:edit_notice] = I18n.t('student.member_disinvited')
```

**Comment by alexinman** [comment]
@david-yz-liu Should the flash message look like this?
![screen shot 2016-01-16 at 1 07 47 pm](https://cloud.githubusercontent.com/assets/6303087/12373750/3c238476-bc52-11e5-8426-37a27e6cbcef.png)

**Comment by david-yz-liu** [comment]
That looks great.
