### ISSUE TITLE
marks spreadsheet error loading csv file with a column name changed

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2275]
When I was testing #2112, I encountered an error under the following scenario.
1. Download a marks spreadsheet with some grades added but not all.
2. Open in Excel, change the name of a column, and save.
3. When I open it in vi, I notice there are no quotes for empty cells.
4. Upload the file into the same spreadsheet.  

The following error occurs:
undefined method `empty?' for nil:NilClass
Extracted source (around line #153):

```
  else
    if old_grade.nil? &&
       (grade_for_grade_entry_item || !grade_for_grade_entry_item.empty?)

      grade = grade_entry_student.grades
              .find_or_create_by(grade_entry_item_id: grade_entry_item.id)
```

Rails.root: /home/vagrant/Markus
Application Trace | Framework Trace | Full Trace

app/models/grade_entry_student.rb:153:in `block in create_or_update_from_csv_row'
app/models/grade_entry_student.rb:126:in`each'
app/models/grade_entry_student.rb:126:in `create_or_update_from_csv_row'
app/models/grade_entry_form.rb:285:in`block in parse_csv'
app/models/grade_entry_form.rb:281:in `parse_csv'
app/controllers/grade_entry_forms_controller.rb:322:in`block in csv_upload'
app/controllers/grade_entry_forms_controller.rb:320:in `csv_upload'

**Comment by czack810150** [comment]
I tried the above but couldn't reproduce the same error. As mentioned above, if one opens the csv with excel and makes changes, the empty cells will no longer have "", but MarkUs doesn't seem to complain about it. I could still upload the modified csv and the change would be reflected without throwing any error.
