### ISSUE TITLE
Assignment rules doesn't line wrap correctly

### ISSUE THREAD

**Issue by tsimica** [MarkUsProject/Markus#2291]
In the student interface show under Assignment Rules, the description and message don't line wrap correctly (depending on your resolution).

**Comment by tsimica** [comment]
Working on this.

**Comment by alexinman** [comment]
@david-yz-liu Just to make sure I'm understanding the problem correctly:
![screen shot 2016-01-16 at 9 22 31 am](https://cloud.githubusercontent.com/assets/6303087/12372846/eadc64f8-bc32-11e5-9a1b-f97b357c5392.png)

**Comment by david-yz-liu** [comment]
That's the issue I had. I'm not sure if @tsimica had a different issue though.
