### ISSUE TITLE
One Group per Student

### ISSUE THREAD

**Issue by bruceiv** [MarkUsProject/Markus#2297]
I ran head-on into the CSV upload issue most recently reported in #2237 and am now entering groups for 225 students by hand. I would like a feature where you can have the system automatically set up one group per student, with one button push (it seems like the common case, and also the intent of everyone who's getting jammed up on CSV upload).

**Comment by reidka** [comment]
That is the plan.  The workaround we have been using is to use a firefox add-on, imacros for creating groups with one student.  The group and repo get created when the student navigates to the assignment.   Using "switch role" and imacros, we can program the browser to login as each student and navigate to the relevant assignment page.

**Comment by reidka** [comment]
Done in #2376 and #2414
