### ISSUE TITLE
Editing annotation adds extra paragraph tags

### ISSUE THREAD

**Issue by xiaochuanyu** [MarkUsProject/Markus#2304]
Editing an annotation will add a surrounding paragraph tag to the text.
Multiple edits add more tags.
![test](https://cloud.githubusercontent.com/assets/1718745/10260642/03da3694-6948-11e5-8711-8476c304d0d5.png)
The tags are also visible in popup.
![test](https://cloud.githubusercontent.com/assets/1718745/10260661/511dc808-6948-11e5-9d89-1fb503847035.png)

**Comment by wkwan** [comment]
I can't seem to edit annotations in the first place. Get this;

POST http://0.0.0.0:3000/en/annotations/update_annotation 404 (Not Found)

**Comment by Sm1th** [comment]
Can't reproduce, editing annotations work fine.

**Comment by david-yz-liu** [comment]
Thanks, @Sm1th.
