### ISSUE TITLE
Use markdown as language for annotations

### ISSUE THREAD

**Issue by xiaochuanyu** [MarkUsProject/Markus#2305]
Would be nice if markdown can be used as the language for writing annotations.
For example, the library [RedCarpet](https://github.com/vmg/redcarpet) can be used for rendering markdown to html (I assume this is a rails app, correct me if I'm wrong).

**Comment by finnergizer** [comment]
I'm working towards this. Thank you for the start. I'm also looking at client-side solutions. Particularly, 
https://github.com/chjj/marked
https://github.com/evilstreak/markdown-js

**Comment by arkon** [comment]
May also be noteworthy: https://github.com/github/markup
