### ISSUE TITLE
Useless Nested Vertical Scrollbar in Large JPGs

### ISSUE THREAD

**Issue by wkwan** [MarkUsProject/Markus#2308]
When a large JPG is uploaded, there's an inner vertical scrollbar that barely moves. Also, the horizontal scrollbar will not be visible until you scroll to the bottom.

![screen shot 2015-10-04 at 3 42 51 am](https://cloud.githubusercontent.com/assets/2907892/10266921/48bf4bb6-6a4a-11e5-9814-54b9a9fbc7d6.png)
![screen shot 2015-10-04 at 3 44 41 am](https://cloud.githubusercontent.com/assets/2907892/10266925/6322ab6a-6a4a-11e5-8f9d-f52b312ed583.png)

**Comment by arkon** [comment]
I attempted to fix issues with this earlier in #2137 but it wasn't quite perfect. Feel free to take a look at the code in there and see if you can get it working nicely?

**Comment by mishaschwartz** [comment]
Reason to mark as invalid:

- cannot reproduce (tried with Chrome, Firefox, Safari)
