### ISSUE TITLE
Marks Spreadsheet Upload with incomplete lines

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#2324]
From Dan:

Uploading a marks spreadsheet where a line looks like
zingarod,
e.g. no mark after someone's utorid, causes a nil exception.

This can happen in a file when one or more students are in the classlist 
but don't write the test. e.g. I just got a file back from my TAs where 
some lines had just a utorid and comma but no mark because they didn't 
write the test.

**Comment by reidka** [comment]
Closed by #2412
