### ISSUE TITLE
Less than or equal sign does not appear in comments.

### ISSUE THREAD

**Issue by ostrokach** [MarkUsProject/Markus#2335]
Whenever I put a "<=" in a comment in student code, it does not get rendered. If I put "<=" inside a \<code\> block, nothing gets rendered on the line after "<=".

**Comment by reidka** [comment]
This happens when annotation pdf files.

**Comment by ostrokach** [comment]
I think I was annotating python .py files?

**Comment by reidka** [comment]
Hmm.  I can't replicate it when adding annotations to code files, but I do see the problem when adding an annotation for a pdf file.

**Comment by WilsonChiang** [comment]
Working on this. Also could not replicate this on .py files.
