### ISSUE TITLE
Using a csv file to create groups should only allow creation of brand new groups

### ISSUE THREAD

**Issue by binuri** [MarkUsProject/Markus#2338]
For all entries in the csv file, if the group already exists or if any of the members are part of a different group for the current assignment/does not exist in the student db, or if the repo name is already taken by a different group, don't create the group and show an error

**Comment by reidka** [comment]
Now that I'm looking at this more carefully, I can see problems with the approach.  If an instructor accidentally deletes a group there is no way to recover it.
1) If group name and repo match in the csv file and an existing group, and the group does not belong to a grouping, then we should allow it.  (The membership is lost when the grouping is deleted.)
2) If the group name and repo match in the csv file and an existing group.  If the group belongs to a grouping from another assignment and the student membership matches the csv file then we should allow it.

(I'm going to look at this further, but these are initial thoughts.)

**Comment by reidka** [comment]
Fixed in #2343
