### ISSUE TITLE
Collect and grade this revision does not work in Chrome

### ISSUE THREAD

**Issue by WilsonChiang** [MarkUsProject/Markus#2342]
The collect and grade this revision button in the Submissions Repository browser does not seem to work in Chrome. Works fine in Safari for me. Probably related to the "Are you sure" javascript prompt.

**Comment by dmitrykhabarov** [comment]
Can't reproduce

**Comment by reidka** [comment]
Tried this on several machines and can't reproduce it.

**Comment by arkon** [comment]
Random thought: if the user sets it so a site stops showing alert/prompt popups, it's possible that it's just not shown so nothing will ever happen.

**Comment by reidka** [comment]
Good point, but I'm not sure if we can do anything about it.
