### ISSUE TITLE
Remove Prototype code

### ISSUE THREAD

**Issue by arkon** [MarkUsProject/Markus#2351]
Seems like there's still some minor traces of Prototype lingering around in:

- [x] `automated_tests_helper.rb`
- [x] `_test_result_window.html.erb`
- [x] `_test_selector.html.erb`

EDIT:
- [x] `_overall_remark_comment.html.erb`
- [x] `file_manager.html.erb`
- [x] `repo_browser.html.erb`

**Comment by melneubert** [comment]
Sorry, looks like I missed those ones. I can look into this.

**Comment by arkon** [comment]
Also #2381

**Comment by arkon** [comment]
Added 3 more files that I missed before to the OP.

(cc @melneubert )

**Comment by david-yz-liu** [comment]
@alexvail You already fixed `_overall_remark_comment.html.erb`, and please do the same for `file_manager.html.erb` and `repo_browser.html.erb`.
