### ISSUE TITLE
No way to collect individual assignments

### ISSUE THREAD

**Issue by bruceiv** [MarkUsProject/Markus#2354]
Due to a technical glitch I had some students submit assignments after I ran a "collect all assignments" (including theirs) and graded everyone else's work. I can upload their assignments to their group repository, but I can't actually collect them again, because there's no way to collect individual assignments. I tried assigning the students to their own section so that I could collect by section, but that simply made the Submissions page crash with the following error:

```
 NoMethodError in Submissions#browse

Showing /u7/markus/markus_cs343_f/markus-1.0-rc1/app/views/submissions/submissions_table_row/_table_row.html.erb where line #67 raised:

undefined method `due_date' for nil:NilClass

Extracted source (around line #67):

64:     <% else %>
65:       <%= image_tag 'icons/error.png',
66:                     :title => t(:past_due_date_edit_result_warning,
67:                                 :href => t(:last_commit)) if grouping.past_due_date? %>
68:       <%= I18n.l(grouping.current_submission_used.revision_timestamp :format => :long_date) %>
69:     <% end %>
70:     </td>

Trace of template inclusion: app/views/submissions/_submissions_table_body.html.erb, app/views/submissions/browse.html.erb

Rails.root: /u7/markus/markus_cs343_f/markus-1.0-rc1
Application Trace | Framework Trace | Full Trace

app/models/grouping.rb:617:in `past_due_date?'
app/views/submissions/submissions_table_row/_table_row.html.erb:67:in `_app_views_submissions_submissions_table_row__table_row_html_erb__1967020366_69919543016000_15065836'
app/views/submissions/_submissions_table_body.html.erb:3:in `_app_views_submissions__submissions_table_body_html_erb__295118777_69919543031100_16475372'
app/views/submissions/_submissions_table_body.html.erb:2:in `each'
app/views/submissions/_submissions_table_body.html.erb:2:in `_app_views_submissions__submissions_table_body_html_erb__295118777_69919543031100_16475372'
app/views/submissions/browse.html.erb:166:in `_app_views_submissions_browse_html_erb__444457625_69919544043180_0'

Request

Parameters:

{"per_page"=>"30",
 "locale"=>"en",
 "page"=>1,
 "assignment_id"=>"3",
 "sort_by"=>"group_name",
 "filter"=>"none"}

Show session dump

Show env dump
Response

Headers:

None
```

**Comment by reidka** [comment]
Try going to the repo view, to collect a particular revision for an individual.

(We will have to fix the crash though)

**Comment by alexinman** [comment]
I am unable to reproduce this error.
The file `submissions/submissions_table_row/_table_row.html.erb` doesn't seem to exist anymore, which is where the error was occurring. 
I tried collecting and grading all assignments, then uploading another file to a students repository and added them to a section. The submissions/browse page loads fine but I don't see a way to collect a single sections assignments so I couldn't try that.

**Comment by david-yz-liu** [comment]
Thanks, @alexinman. @bruceiv thank you for the message - it seems you were using an older version of MarkUs. I was also unable to reproduce the error on our latest version.
