### ISSUE TITLE
Download all submissions only downloads some of the submissions

### ISSUE THREAD

**Issue by jmzaleski** [MarkUsProject/Markus#2359]
I habitually "collect all" then immediately "download all" submissions.
I do things this way because for 300 we mark essays on paper, so all I really want to do is download to print out the papers for the TA's to mark.

Last week, Nov 9, I collected and downloaded all the A3.

Today I learned that I was missing 17 papers.
Interestingly, one of the TA's (Alicia) downloaded today, and had them all.

My theory (which is mine) is that markus is attempting to zip and download before the collect is fully completed.

http://www.cs.toronto.edu/~matz/markus-issue/A3_matz.zip
http://www.cs.toronto.edu/~matz/markus-issue/A3_matz%20(1).zip

**Comment by arkon** [comment]
I feel like posting all of the assignments is a privacy concern...

I have the same theory for the issue though.

**Comment by jmzaleski** [comment]
Good point did you download them into somewhere private and I will delete
that directory on the server

**Comment by jmzaleski** [comment]
I changed the perms so the zip files are private.
However, I added two (readable) files that  might provide all the clues you need:

http://www.cs.toronto.edu/~matz/markus-issue/A3_matz%20(1).zip.list
http://www.cs.toronto.edu/~matz/markus-issue/A3_matz.zip.list

**Comment by reidka** [comment]
The collection process happens in the background, so you are likely getting a race condition.

David and I talked about this briefly.  I think we should add some ajax calls to refresh the page until collection is completed.
