### ISSUE TITLE
missing PDF file from zip file

### ISSUE THREAD

**Issue by jmzaleski** [MarkUsProject/Markus#2367]
Hi, on csc301, A3, I collect all submissions. download the zip file, and there is one missing:

No PDF file appears in the zip file for g5jiangw.
Yet, if I navigate to the folder corresponding to the user the GUI has a file (which i can download)

Additional fact: There is a little yellow warning (?) badge on the submission
The tooltip says that the last commit was after the due date.. but it wasn't??

![g5jiang](https://cloud.githubusercontent.com/assets/9355220/11349878/acd2d45e-91fc-11e5-85e4-a6939438e122.jpg)

**Comment by reidka** [comment]
@jmzaleski Was this related to the problem that the collection was not complete?

**Comment by jmzaleski** [comment]
almost certainly.

Mathew Zaleski BA5222 416-978-1712

**Comment by reidka** [comment]
Then this is related to #2359, and will be addressed by our fix for that.
