### ISSUE TITLE
Remark request overall comment causes Javascript Error - Cannot save

### ISSUE THREAD

**Issue by finnergizer** [MarkUsProject/Markus#2381]
![screen shot 2015-12-07 at 1 39 20 pm](https://cloud.githubusercontent.com/assets/4589389/11636031/01333822-9ce8-11e5-9827-a8a7fc22dadc.png)

Changed it to jQuery, and then it switched to enabled function not being defined (apparently this functionality does not come out of the box with jQuery).

**Comment by melneubert** [comment]
@finnergizer Were you planning on taking this one? I have a fix already that I can push if you like - just let me know.

**Comment by finnergizer** [comment]
@melneubert  

I changed it to

```
onkeypress: "jQuery('#overall_remark_comment_submit').attr('disabled',false);" %>
```

but I am not sure if that is a total fix as it does not revert to be disabled on a successful save. How did you end up fixing it?

**Comment by melneubert** [comment]
@finnergizer 
Oh that's the same solution I had, I didn't realize it was not reverting on successful save - that may require a bit more work.

**Comment by melneubert** [comment]
@finnergizer  Reverting it back can be accomplished by adding  

```javascript
onclick: "jQuery('#overall_remark_comment_submit').prop('disabled', true);"
```
as part of the overall_remark_comment_submit portion further below in that file.

**Comment by finnergizer** [comment]
Yea I was also thinking of an onclick listener but wasn't sure if it would be preferable to add a callback on success of the form submission. It would be a more involved solution, but that way it would indicate that the changes have actually been saved (whereas I think with an onclick the following form submission could fail and the changes not actually be persisted).
