### ISSUE TITLE
Disabling alerts

### ISSUE THREAD

**Issue by samirp91** [MarkUsProject/Markus#2384]
When the markus tab is kept open for a long period of time, an alert pops up and interrupts whatever is going on. There should be an option where the alert could be turned off.

**Comment by reidka** [comment]
Do you mean the alert that says that the session is about to end?  (We added that so TAs would not add annotations or marks when the session was ended and their work would be lost when the page was refreshed to tell them that they need to log in again.)
If the markus tab does not have focus, does the alert interrupt the currently open tab?
What browser are you using?
Thanks.

**Comment by samirp91** [comment]
It interrupts whatever I am doing whether I'm using the browser or not. I'm using chrome. Also my suggestion was not to disable it completely but have the option to disable it.

**Comment by qasim** [comment]
Could [this](https://developer.mozilla.org/en-US/docs/Web/API/notification) be an alternative method of notifying the user?

**Comment by arkon** [comment]
I don't think notification support is good enough to be a valid alternative.

**Comment by qasim** [comment]
For reference, the browser support table for notifications is located [here](http://caniuse.com/#feat=notifications).

**Comment by david-yz-liu** [comment]
Fixed in #3448.

**Comment by arkon** [comment]
Also worth mentioning the behaviour of browser dialogs changed in recent(ish) versions of Chrome, so it's a bit of a non-issue: https://developers.google.com/web/updates/2017/03/dialogs-policy
