### ISSUE TITLE
consider generating candlestick chart for class statistics

### ISSUE THREAD

**Issue by jmzaleski** [MarkUsProject/Markus#2397]
I do this from downloaded CSV files using R roughly like so:

args <- commandArgs(trailingOnly = TRUE)
marks <- read.csv(args[1])
tut <- as.matrix(marks[3])
grade <- as.matrix(marks[4])
pdf(args[2])

print("mean")
mean(grade)

hist(grade, main=args[1])
boxplot(grade ~ tut)
print ("anova summary")
summary(aov(grade ~ tut))

nb. https://en.wikipedia.org/wiki/Candlestick_chart

**Comment by david-yz-liu** [comment]
I agree this is useful for instructors, but IMO it is outside the scope of MarkUs. I think it's best to keep more complex statistics/visualizations in scripts that process MarkUs' csv files.

**Comment by jmzaleski** [comment]
I've always used my own R script for this. it's a royal pain.
