### ISSUE TITLE
Students added to group did not appear until refresh

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2398]
Students being added to the group didn't appear to be added until the page was refreshed.
This occurred on Chrome.
This was attempted after the marks were released.
Students had previously been in a group but were manually removed.
(Not sure which of these details are relevant)

This happened to Tom in CSC108

**Comment by alexvail** [comment]
I tried to reproduce the issue but wasn't successful.
I tried many combinations of actions.

Removing 2 student from the same group, creating a new group, adding the 2 students to it
Removing 2 student from 2 different groups, creating a new group, adding the 2 students to it
Removing 2 student from the same group, adding the 2 students in an existing empty group
Removing 2 student from 2 different groups, adding the 2 students in an existing empty group

Tried these 4 combinations with marks released & not released, to no avail.

**Comment by reidka** [comment]
Couldn't reproduce.
