### ISSUE TITLE
Allow students to create groups after the deadline has passed

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2417]
This is possibly controversial.  

Right now, a group is created when a student logs into MarkUs and navigates to the assignment.  (If the instructor creates the groups or the assignment is an individual assignment and the instructors "creates all groups" this isn't an problem.)

Sometimes students don't log into MarkUs until after the deadline, so no group is created.  The instructor has to explicitly create the group and add the student to it.  The solution is to allow the student to create the group even after the deadline has passed.  The submission will show up as uncollected in the instructor view.

**Comment by mishaschwartz** [comment]
Reasons to mark this as invalid:

- This has been discussed several times (since 2016) most recently when we introduced grouping extensions and it was decided that requiring creating a group after the deadline is an action that should require communication between the student and instructor.
