### ISSUE TITLE
remarks rake task is broken

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2435]
I think this is a result of refactoring in #2423 
@aclar48 could you please take a look?

The error message is
ActiveRecord::UnknownAttributeError: unknown attribute 'remark_result_id' for Submission.

**Comment by reidka** [comment]
Looks like it broke a lot of tests too.

**Comment by david-yz-liu** [comment]
I fixed the tests in a separate PR. Didn't do the take task though.

**Comment by aclar48** [comment]
#2436
