### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2446]
At Toronto, we have never really made good use of sections, and have never had much motivation to do so, but the usefulness of subdividing a class into sections on several possible dimensions is more appealing as the class sizes increase.

With respect to MarkUs features, here are the things that sections can give us.

- Different sections may have different deadlines for specific assignments
- Students might be allowed to invite group members only from their own section  (The option for this needs to be added to the assignment properties.)
- One or more graders may be assigned to a section
- A marks spreadsheet could be filtered by section
- An admin might want to collect for a particular section.

The open issues with sections:
#2354
#1676
#1219
#2448
#2449

**Comment by alexinman** [comment]
#2458

**Comment by alexinman** [comment]
Are there any other issues/features that you would like to be fixed/added to Sections? The original list has been completed (with a few PRs still being reviewed).
