### ISSUE TITLE
Add the ability to assign a grader to a section

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2449]
This will take some thought about what the UI should look like.

**Comment by alexinman** [comment]
Hey, just read this one now. This is a brand new feature, correct?
Where would the UI for this be and where/how would it affect everything?
We can talk on Monday's meeting for more details, if that would be easier than explaining everything here. :)

**Comment by alexinman** [comment]
@david-yz-liu So, just clarifying what you said yesterday.
Currently this is what the Assignment>Graders Tab looks like, with the ability to filter by sections:
![screen shot 2016-03-15 at 9 33 02 am](https://cloud.githubusercontent.com/assets/6303087/13777863/5b5d7280-ea91-11e5-9b82-2b8f4860e4ac.png)
Do you want me to add that functionality to the Quiz>Graders Tab? Which currently looks like this:
![screen shot 2016-03-15 at 9 32 35 am](https://cloud.githubusercontent.com/assets/6303087/13777879/74faabd6-ea91-11e5-8f85-e1f6c0100095.png)
And would you also like me to add it to the Marks Spreadsheets? Which currently looks like this:
![screen shot 2016-03-15 at 9 32 27 am](https://cloud.githubusercontent.com/assets/6303087/13777888/87d60f48-ea91-11e5-9794-ce2d29d7bd52.png)

**Comment by david-yz-liu** [comment]
1) The sections should appear in the graders tab.
2) The "Grades" table should not have filters, but it should be possible to sort by the Section column.

**Comment by alexinman** [comment]
Alright :+1:
