### ISSUE TITLE
Grade Histograms for students

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2450]
It would be nice to have the option to display a histogram of the marks for an assignment to students to give them an idea of the distribution of marks.

We have to be careful that the size of the class is big enough that the histogram doesn't inadvertently give away information.   

I think that a bucket size of 10% is probably the smallest we want to go.
We probably need to precompute the histograms so that they don't get computed everything a student logs in.

**Comment by david-yz-liu** [comment]
(Closing for now as stale)
