### ISSUE TITLE
Should a public key file be deleted when it's entry in the database is deleted?

### ISSUE THREAD

**Issue by Sm1th** [MarkUsProject/Markus#2455]
Currently they are not, and so you have a build up of public key files in the `/data/dev/keys` dir (for the development environment.)

**Comment by reidka** [comment]
Yes, that sounds like a good idea.  I can't think of any reason to keep the file.

**Comment by Sm1th** [comment]
Ok. Similarly, when a public key file is deleted from the `keys` dir, should the corresponding key_pair database record be deleted?

**Comment by reidka** [comment]
Yes, but we have to be careful about code ordering then.  Under what circumstances would the file be deleted? It should only be deleted in conjunction with deleting the database record.

**Comment by david-yz-liu** [comment]
@Sm1th I added a new label you can use for Git issues. :)

I don't want you to worry about what happens if the public key is deleting from the file system manually. We will generally make sure to only interact with the public keys through the MarkUs application.

**Comment by Sm1th** [comment]
@david-yz-liu I can't actually add labels to anything :(.

And ok that sounds good, I was thinking the same thing.

**Comment by Sm1th** [comment]
This issue can be closed!
