### ISSUE TITLE
NoMethodError when trying to browse submission repo when admin

### ISSUE THREAD

**Issue by Sm1th** [MarkUsProject/Markus#2456]
To reproduce:

1. Be logged in as admin
2. Go to submissions tab for an assignment  
    ex: http://0.0.0.0:3000/en/assignments/3/submissions/browse
3. Click on a **git** repository
4. Receive this error:
![screen shot 2016-01-28 at 1 50 05 pm](https://cloud.githubusercontent.com/assets/3375071/12653492/3100696a-c5c6-11e5-8619-27c2cdfe8c2d.png)

I will look into this bug.

**Comment by aclar48** [comment]
@Sm1th  do you have Gitolite setup and running on your machine? I have it setup and do not get that error

**Comment by Sm1th** [comment]
@aclar48 Yes I do. Make sure your development.rb file has 'git' as REPOSITORY_STORAGE, and that you `rm -rf data/dev/repos/*` then run `bundle exec rake db:setup`. Then see if you get the error, please.
