### ISSUE TITLE
markus assignment import changes times (csv format)

### ISSUE THREAD

**Issue by jmzaleski** [MarkUsProject/Markus#2457]
I downloaded assignment as csv from last term.
edited them, and imported into this term's markus. 
Dates okay, but a few of the times moved by two hours??

(I had to attach the .csv as a zip. github doesn't like csv attachments)

![markus-after-assignment-import-screenshot](https://cloud.githubusercontent.com/assets/9355220/12678570/673f2e38-c66d-11e5-8c54-ecfa6eca29d3.jpg)
[assignments_hacked.csv.zip](https://github.com/MarkUsProject/Markus/files/109896/assignments_hacked.csv.zip)

**Comment by jmzaleski** [comment]
hmm. is this a daylight savings time thing? (sept was summer time, today is winter time)

**Comment by david-yz-liu** [comment]
Thanks, @jmzaleski. I'll look into this - doesn't seem like DST is encoded in the csv, but I could be wrong.
