### ISSUE TITLE
Student view error when Marks Spreadsheet has a "total mark" of 0

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#2463]
Steps to reproduce:

1. Create a marks spreadsheet with one column with a "total mark" of 0.
2. Enter a grade for a student (could be any number).
3. Release the grade for the student.
4. Login as the student. The assignments page has a runtime error.

**Comment by alexvail** [comment]
Can't seem to reproduce this one. See screenshots below. I also different combinations such as putting the column with a total mark of zero between two other column, or as the last, still didn't get errors.

![1](https://cloud.githubusercontent.com/assets/8976280/13730065/f890c822-e91a-11e5-8523-2f75e2c7dffc.png)
![2](https://cloud.githubusercontent.com/assets/8976280/13730064/f890bf80-e91a-11e5-9505-7009f4af443e.png)
![3](https://cloud.githubusercontent.com/assets/8976280/13730066/f8913dc0-e91a-11e5-8491-c938192ff32e.png)

**Comment by reidka** [comment]
I also can't reproduce this.  Thanks @alexvail
