### ISSUE TITLE
observed interesting behaviour when "collecting all"

### ISSUE THREAD

**Issue by jmzaleski** [MarkUsProject/Markus#2467]
I just did a collect all..
when the view updated I was surprised that the last students didn't have  a little pencil icon.. he/she still had a blue box.
I stared at this for a few seconds, refreshed the screen (with browser refresh) and lo and behold the last student got a yellow pencil too.

hope this is a clue to some race condition..

**Comment by reidka** [comment]
Collecting happens in the background, so the first update to the view doesn't necessarily happen when the collection is complete.  We clearly need a visual clue that collecting is still in progress.
