### ISSUE TITLE
Assignment folder doesn't get committed when assignment is created [git]

### ISSUE THREAD

**Issue by Sm1th** [MarkUsProject/Markus#2513]
Because the assignment folder is empty when it is first created, it doesn't get added to the git repository. (Git doesn't track empty directories).

An easy way to fix this issue is to commit some sort of README file when an assignment is created, maybe containing the assignment name and the contents of the message field if it was provided. Or maybe the assignment creator could upload a file containing the assignment description.

**Comment by david-yz-liu** [comment]
Let's commit a `.gitkeep` file to the directory. I thought this had already been done, but oh well.

**Comment by Sm1th** [comment]
Okay. This should be done in the `create_grouping_repository_folder` function in `grouping.rb` right?
