### ISSUE TITLE
Sort by section doesn't work in Spreadsheet tables

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#2522]
It seems like the column is sortable (has the little arrows), but the order of rows is unaffected when the column is clicked.

**Comment by alexinman** [comment]
I am unable to reproduce this issue. Sorting by section works fine for me.
What browser are you using?

**Comment by david-yz-liu** [comment]
It's possible you haven't tried to sort when some students are in sections, and others are not.
