### ISSUE TITLE
Git problem with bad keys

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2535]
Obviously uploading a bad public key will cause problems.  However, if the bad public key is not removed, then even if a valid public key exists, git commands can't be used, and the error message is confusing.

I think we could do a check before accepting the uploaded key.  gitolite runs
ssh-keygen -l -f KEYFILE

to produce a fingerprint.  It then matches it against a regular expression:
`$fp =~ /([0-9a-f][0-9a-f](:[0-9a-f][0-9a-f])+)/ or $fp =~ m(SHA256:([A-ZA-z0-9+/]+));`

(=~ is  perl for regex matching)

I think we should do the same thing before accepting the public key.  Stupid things like cutting and pasting with inserted newlines can cause problems.

**Comment by adisandro** [comment]
This can be closed, gitolite is gone.
