### ISSUE TITLE
 Numbers on assignment grades summary do not match the graph

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2543]
From a user:
"How to reproduce: In the instructor view, there's some assignment statistics page somewhere that shows the grade distribution and the number of people who got a grade of zero, among other things.
Expected result: The written data in the sidebar should match the data displayed in the graph.
Actual result: The data in the sidebar is counted over individual students, while the data in the graph represents statistics for individual submissions, so in the sidebar grades for groups of two are double-counted."

The data in both should be represented per group.
Assignments submitted and Assignments graded seem fine, but Number of Fails is incorrect. 
(I didn't check the other numbers but they should be double-checked.)

**Comment by mishaschwartz** [comment]
Reason to mark as invalid:

- this has been resolved but the issue was not closed (both the histogram and side panel data are calculated per grouping)
