### ISSUE TITLE
Notes cannot be removed from the assignment grading page where they were added

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2548]
A user reports:
"How to reproduce: In the TA view, click the name of an assignment that has been collected and click the name of a group. Click the Notes(0) link. Type some text into the text box and click Save Note. Now click the Notes link again.
Expected result: There should be an option next to the saved note to delete it.
Actual result: The note can only be deleted by navigating to the global Notes tab at the top of the application and choosing to delete it from there."

**Comment by david-yz-liu** [comment]
Fixed in #5128.
