### ISSUE TITLE
Add a column for bonus and deductions on the Summaries view

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2550]
This would help identify students who received deductions or bonuses more easily for comparison.

**Comment by bzhou26** [comment]
I submitted a pull request to add a column to show bonus/deductions other than late penalty. If it is need to add to this column or to show the late penalty in another column, please let me know.

**Comment by david-yz-liu** [comment]
Thanks, @bzhou26. We definitely want the late penalty to appear as well, but not in a separate column. Rather, you can simply combine the extra_points and extra_percentage into one column.
