### ISSUE TITLE
Strings with multiple lines in locales need to be line-broken

### ISSUE THREAD

**Issue by christinem** [MarkUsProject/Markus#2571]
Me and @GitGeminiano found an issue where, if React tried to render a string from one of the locales (language) files that was split into multiple lines (with no backslash for line breaks), JSXTransformer would complain and throw an error and fail to render the rest of the page. Putting a line break in the string fixed it. We probably want to go through the language files and do that for all strings which are split into multiple lines.

**Comment by david-yz-liu** [comment]
This shouldn't be an issue now that we use `i18n-js`.
