### ISSUE TITLE
Update of marking scheme when an assignment has been just created 

### ISSUE THREAD

**Issue by GitGeminiano** [MarkUsProject/Markus#2602]
How to reproduce:
Log in as an admin.
Click on add assignment, create a new assignment with Rubric marking scheme, click on submit.
Click on the marking scheme tab.
Add a few criteria.
Try clicking one of the links for a criteria that is not the one being displayed.

Expected result: The form on the right should be updated.

Actual result: Nothing changes.

This happens both in Mozilla Firefox and Google Chrome

**Comment by christinem** [comment]
This doesn't seem to happen anymore.
