### ISSUE TITLE
Apache mirror going down causing tests to fail, add a backup mirror

### ISSUE THREAD

**Issue by WChrisK** [MarkUsProject/Markus#2606]
Tests are failing on Travis with:
`The command "wget http://apache.mirror.iweb.ca/subversion/subversion-1.9.4.tar.gz" failed and exited with 8 during .`

Could possibly update this by checking if it fails and maybe using a backup, like `http://www-us.apache.org/dist/subversion/subversion-1.9.4.zip`, or rather any link from: https://www.apache.org/mirrors/ ?

**Comment by david-yz-liu** [comment]
I've updated the URL. A more permanent solution would be nice, but I don't have the cycles to do this right now.
