### ISSUE TITLE
Class average rounding different to 'your mark' rounding

### ISSUE THREAD

**Issue by ghost** [MarkUsProject/Markus#2683]
After seeding and making a new server, if you mark one single student submission and release only that one, the averages are off by 0.01 sometimes:

`Your mark: 28.12% (Class Average: 28.13%)`

**Comment by MBAustin** [comment]
I couldn't reproduce this (I set up an assignment whose criteria added up to 2500, gave a student 703/2500 which is 28.12%, and the system shows: Your mark: 28.12% (Class Average: 28.12%)), could you provide more details about how to cause the bug?
