### ISSUE TITLE
Bad Gateway returns when selecting any assignment

### ISSUE THREAD

**Issue by Korshev** [MarkUsProject/Markus#2713]
In the assignment tab whenever I click on any assignment a "Bad Gateway" message is returned.

![capture](https://cloud.githubusercontent.com/assets/16843757/17840313/2ca9880a-67c0-11e6-9f65-911c7c7087f9.PNG)
![capture2](https://cloud.githubusercontent.com/assets/16843757/17840314/2cad953a-67c0-11e6-9bf1-871f58a7a3c1.PNG)

**Comment by david-yz-liu** [comment]
(Demo should be taken down, it's quite out of date.)
