### ISSUE TITLE
Rubric criterion replaces flexible criterion

### ISSUE THREAD

**Issue by MBAustin** [MarkUsProject/Markus#2724]
After seeding a new server, creating an assignment and adding first a flexible criterion, then a rubric criterion, the rubric criterion appears to replace the flexible criterion (though it does not affect the total mark for the assignment). This can happen more than once in the same assignment as more flexible and rubric criteria are added, but adding a checkbox criterion will cause it to stop happening. Leaving and coming back to the assignment causes the criteria to display normally.

**Comment by david-yz-liu** [comment]
Fixed in #2735
