### ISSUE TITLE
Bug: File extension when downloading subversion repository list

### ISSUE THREAD

**Issue by lungj** [MarkUsProject/Markus#2757]
Clicking the "Subversion checkout file" button results in a file but the file extension of the downloaded file is `.csv.xls`. The most appropriate file extensions are `.sh` or perhaps `.txt`.

OS: MacOS 10.12 beta (build 16A313a)
Browser: Safari 10.0 (12602.1.50.0.8)
MarkUs version: 1.5.0.DEV
Ruby version: 2.2.5
Rails version: 4.2.4

**Comment by adisandro** [comment]
The checkout file has no extension at present.
