### ISSUE TITLE
Bug: Unable to download student list as CSV

### ISSUE THREAD

**Issue by lungj** [MarkUsProject/Markus#2764]
Clicking the "download" button in order to download a student list as CSV results in the following error:

```
NoMethodError in StudentsController#download_student_list
undefined method `generate_csv_list' for #<Class:0x0000000486be20>

Extracted source (around line #107):
105
106
107
108
109
110

    case params[:format]
    when 'csv'
      output = User.generate_csv_list(students)
      format = 'text/csv'
    when 'xml'
      output = students.to_xml
```

System details:

```
You are using MarkUs version: 1.5.0.DEV

Ruby version: 2.2.5

Rails version: 4.2.4
```

**Comment by david-yz-liu** [comment]
@lungj I fixed this one on the master branch. If you want to use this for the current term or next term, please let me know so that we can patch the running instances.

**Comment by lungj** [comment]
Thanks, @david-yz-liu . I've been using an alternate class list to generate a CSV file so this issue doesn't adversely impact me.
