### ISSUE TITLE
Standardize appearance of flash messages in UI

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#2779]
Right now, there's a semi-standard place where flash messages appear (under `views/shared/_flash_message`), but this isn't being used consistently, and in particular almost never being used by AJAX requests that want to display a message.

A few things to fix this:
- [x] Check that all main UI views render this (should be trivial, since I think the two most common layouts, `content` and `assignment_content`, already use them.
- [x] All four divs (for the four different message types) must always be created, hidden if they have no contents.
- [ ] Remove duplicates of these divs that are manually created in certain views
- [x] Always use these in AJAX callbacks to display messages to the user.

**Comment by david-yz-liu** [comment]
@b2simms or @bzhou26 this is a good issue to work on. I couldn't decide who to give it to, so I'm adding it to both projects for now. Upon reflection, it might be good for b2simms to work on the first three parts, and bzhou26 to work on the fourth part.

**Comment by mishaschwartz** [comment]
Reason to mark as invalid:

- this has been resolved by updates to the code since this issue was created
