### ISSUE TITLE
Uploading HTML file to markus system is modified.

### ISSUE THREAD

**Issue by sooham** [MarkUsProject/Markus#2782]
**Replication:**
Upload HTML file as assignment submission to markus.
download said HTML file from the markus system.

**Issue:**
Markus modifies the original HTML by placing source HTML in <pre> tags,
forcibly showing source instead of rendered HTML.

May be as intended, but it is impossible for a student to send a HTML file as-is
to professor or marker.

**Comment by sooham** [comment]
How I found it: uploaded assignment consisting of a HTML page, marker couldn't open it. Got 10% penalty :'(.

**Comment by david-yz-liu** [comment]
Closing this one; TAs and admins can download source files to view them in a rendered format. We don't currently plan to implement a "preview" for some file types.
