### ISSUE TITLE
Underscores show up as italics

### ISSUE THREAD

**Issue by ostrokach** [MarkUsProject/Markus#2798]
Underscores show up as italics in the "Source Code" view but not in the "Annotations" view. I think it would be best if underscores where not converted to italics at all (we have '*' for that). 

In Python code, many variable names have underscores. You can escape them with '\', but then '\' show up in the "Annotations" view, which is ugly.

**Comment by arkon** [comment]
I think that since the annotations use Markdown, it _should_ convert things to italics if underscores are used (since that's just how Markdown is). If you need to have variable names with variables, you could probably use backticks instead, so they'd be like `this_awesome_variable_name`.

**Comment by ostrokach** [comment]
Underscores get interpreted even if you use backticks!

**Comment by christinem** [comment]
@ostrokach I use backslashes to escape my underscores and it fixes the italics problem, and the backslashes don't show for me in the annotations view.

**Comment by david-yz-liu** [comment]
We updated the process by which annotations are parsed under Markdown, so this issue seems to have been resolved by that.
