### ISSUE TITLE
Question: Why support two databases?

### ISSUE THREAD

**Issue by aleccool213** [MarkUsProject/Markus#2800]
I just started looking at this project and it seems from the README and also in some old code, there is support for Postgres and MySql? I was wondering why this is the case. To enforce parity across different instances of the app running, etc etc, isn't is recommended to only support one?

**Comment by david-yz-liu** [comment]
I believe UTSC uses MySQL to run MarkUs, while St. George uses Postgres. This is unlikely to change.

**Comment by aleccool213** [comment]
@david-yz-liu neato, thanks for the answer!
