### ISSUE TITLE
Improvement: Cannot "unselect" a rubric selection once selected

### ISSUE THREAD

**Issue by lungj** [MarkUsProject/Markus#2813]
While marking, once a value has been set for a rubric element, it can only be changed, not unset. Example use case for adding this functionality: two different graders are responsible for marking different elements of an assignment. One accidentally selects a value from the other grader's set of rubric elements. Now, the second grader might believe that that rubric element has been marked and thus fail to properly mark the assignment.

(Ugly) workaround: the first grader sets the rubric mark to 0 and informs the second grader that a mistake has been made. If the second grader fails to mark that rubric element, the student will hopefully notice and complain (since the mark was 0).

**Comment by david-yz-liu** [comment]
Thanks for mentioning this. More commentary in #3331.
