### ISSUE TITLE
Bug: Student files not available to autotesting module.

### ISSUE THREAD

**Issue by lungj** [MarkUsProject/Markus#2815]
I have run the same test cases in MarkUs on submissions (without changing the submissions) and sometimes received an error from the automarker that no student files are present for marking and other times received the expected mark. This could be an automarker bug, but I'm guessing it is a MarkUs bug that results from not syncing (or not waiting for) files passed to the marking system to be written to disk before marking commences.

```
You are using MarkUs version: 1.5.0.DEV

Ruby version: 2.2.5

Rails version: 4.2.4```

**Comment by david-yz-liu** [comment]
This has been fixed!
