### ISSUE TITLE
Bug: Marks for completed tests sometimes not recorded

### ISSUE THREAD

**Issue by lungj** [MarkUsProject/Markus#2816]
I have completed a test run where (all?) students failed ( #2815 ). Normally, students who do not submit anything receive 0 marks and are marked as completed after tests are run. However, in this case, students are receiving no mark (as in, the mark field is empty instead of 0) and results are not being released.

**Edit:** I also have multiple submissions with 6/6 tests passed which is not recorded for some (most) students. The mark is also blank in MarkUs for those students.

This does **not** appear to be related to #2812 in which responses from the marking system containing the NULL character cause MarkUs to abort recording of test results.

**Comment by david-yz-liu** [comment]
Hey @lungj, I've run into this one. The easiest way to fix this for now is to recollect the submissions, and then re-run the tests.

**Comment by lungj** [comment]
Hi @david-yz-liu , do you have any solutions for assignments which also include annotations from TAs (since recollection deletes all their work)? Thanks!

**Comment by david-yz-liu** [comment]
@lungj right. Couple of options here:

1. Have TAs input manually based on the test results. (Annoying, but foolproof.)
2. Re-run tests for those submissions. This should cause the mark to be populated if TAs have already begun marking them - if not, then there's another problem we need to look into. Note that this has the slight downside that two sets of test results will be shown to students, but you could tell students to only look at the most recent set of tests.

**Comment by lungj** [comment]
Thanks, @david-yz-liu ! Option 2 is working fine (previously tested it for another reason and it's working without overwriting results).
