### ISSUE TITLE
Bug: "Grading can begin" appears when grading may be clobbered.

### ISSUE THREAD

**Issue by lungj** [MarkUsProject/Markus#2829]
While using the workaround in #2816 of re-collecting assignments, the "Grading can begin" message appears even while a collection is in progress. However, since grading will be clobbered during this time, the message should not appear.

```
You are using MarkUs version: 1.5.0.DEV

Ruby version: 2.2.5

Rails version: 4.2.4
```

**Comment by mishaschwartz** [comment]
Reason to mark as invalid:

- collecting is run in a background job and job progress is now displayed with flash messages
- the "grading can begin" message is not displayed while reporting job progress
