### ISSUE TITLE
Enhancement: Clear all autotesting grades

### ISSUE THREAD

**Issue by lungj** [MarkUsProject/Markus#2832]
When autotests need to be re-run, because the UI lacks the ability to track progress and because MarkUs appears to be unreliable when it comes to marking, it would be helpful to be able to ensure that new tests have been run. One way of accomplishing this is to remove past results from autotesting (manually triggered or run automatically when a new batch of autotesting occurs).

Without this, one workaround is to upload a new set of unit tests with many test cases that all pass such that the mark assigned as a result is impossible to achieve on the actual assignment. Because no negative marks or permitted and 0 a real mark that students might get, this needs to be a large, positive number. The end result is that all tests that are run with this workaround set of tests get flagged as "erased" (by having an invalid mark). If some are not erased, then it is clear that manually intervention is required to erase the marks. Otherwise, if all marks are successfully replaced with this special marker, the real (new) tests can be uploaded and run until all special marker marks are replaced with real test results.

**Comment by adisandro** [comment]
One can re-collect the student submission to reset all grades.
(but mostly, marking bugs should now be fixed)
