### ISSUE TITLE
Integrating math equation support into Markus

### ISSUE THREAD

**Issue by NelleV** [MarkUsProject/Markus#285]
Teachers from Centrale Nantes would like to be able to add math equations to the annotation of a submission. The tool chosen is MathML.

Documentation on MathML can be found at : http://www.w3.org/Math/XSL/

**Comment by david-yz-liu** [comment]
@paymog You can see in an above comment an old patch; this might be a good starting point for you!

**Comment by paymog** [comment]
Do we know why this wasn't merged into master?

**Comment by david-yz-liu** [comment]
Not sure, but it is certainly possible there is no good reason.
