### ISSUE TITLE
Usability: Horizontal scrolling required for 80 column width, even on widescreen monitor.

### ISSUE THREAD

**Issue by lungj** [MarkUsProject/Markus#2857]
Maximizing browser window in Firefox, Chromium, and Safari on screen with scaled resolution of 1680x1050 does not allow viewing 80 columns of code (horizontal scrolling still required); instead, about 1/3 of screen is occupied by marking rubric. The marking rubric seems like it should be less of a focal point.

**Comment by david-yz-liu** [comment]
@lungj I was working in this code for another problem, and I've made a change to increase the code pane relative size to 70 by default, and fixed the dragging. I'm going to treat that as resolving this issue, though I am certainly aware there are plenty more improvements to make to reduce unnecessary whitespace and maximize the size of the submitted work.
