### ISSUE TITLE
Enhancement: Export/back up instance

### ISSUE THREAD

**Issue by lungj** [MarkUsProject/Markus#2864]
I might try to tackle some MarkUs issues that I can reproduce on an existing MarkUs instance; it would be helpful if I could back up the entire instance (using a MarkUs admin account) and restore on a different machine. Of course, some user account renaming (or built-in account with no external authentication) needs to be used so that authentication can take place on the new machine,

**Comment by mishaschwartz** [comment]
resolved by #5069

- note that #5069 only archives/unarchives files on disk, you will also need to migrate the database manually to the new instance (if using postgres I would recommend the `db_dump` command)
