### ISSUE TITLE
List in overall comments not rendered as list

### ISSUE THREAD

**Issue by arkon** [MarkUsProject/Markus#2895]
It has the correct markup (i.e. `ul` with `li`s), but the styling is wrong.

![screen shot 2017-02-22 at 17 58 25](https://cloud.githubusercontent.com/assets/4098258/23236786/94e6a91c-f928-11e6-855d-56840fecfc52.png)

**Comment by jasonmai** [comment]
Has this been fixed?

**Comment by david-yz-liu** [comment]
Thanks for reporting this. This has now been resolved!
