### ISSUE TITLE
Sorting is done under string semantics and not numerically

### ISSUE THREAD

**Issue by johntiger1** [MarkUsProject/Markus#2897]
Picture should explain all ( I tried sorting the third column from the right; it jumps from 15 to 2)

![markus sorting by 1st digit]
(https://cloud.githubusercontent.com/assets/14852840/23533985/0157cfda-ff83-11e6-9f9a-348fd3f6b57d.png)

**Comment by jasonmai** [comment]
Has this been fixed? I am trying to reproduce it.

**Comment by johntiger1** [comment]
Hi Jason thanks for the reply, I don't think it has been, see this screenshot. I think it only happens on columns that are not the main one. 
![still happening](https://cloud.githubusercontent.com/assets/14852840/25644631/a765197e-2f75-11e7-8882-a9f2240ac0e6.png)

**Comment by david-yz-liu** [comment]
Fixed in #3222. Thanks for reporting this!
