### ISSUE TITLE
Increasing the font size makes the sub-window with marks appear below the code

### ISSUE THREAD

**Issue by lkaratun** [MarkUsProject/Markus#2912]
Increasing the font size above the default browser value (medium in Chrome and 16 in Firefox) makes the sub-window with marks appear below the code (as opposed to to the right of it). The issue occurs here: https://markus.utsc.utoronto.ca/csca48w17/ in Chrome and Firefox. Let me know if I need to provide more info.

**Comment by david-yz-liu** [comment]
This has been fixed in our move to using React for this page (see #3884, #3886).
