### ISSUE TITLE
Confusing dialogue interaction

### ISSUE THREAD

**Issue by GohNicho** [MarkUsProject/Markus#2914]
After adding a file to be uploaded in assignment submission, and attempting to close the window, the following window appears:
![image](https://cloud.githubusercontent.com/assets/5589658/24734519/e9ad0f9c-1a4b-11e7-933b-0ece66a3bbb2.png)

Clicking 'Stay' results in no upload, clicking 'Leave' results in the file being uploaded.
Unsure if this is the intended behaviour, but it's a little bit confusing at least.

**Comment by david-yz-liu** [comment]
Thanks for reporting this, @GohNicho!
