### ISSUE TITLE
Marks Spreadsheet entries randomly turn/stay green for no discernible/documented reason

### ISSUE THREAD

**Issue by gfbee** [MarkUsProject/Markus#2925]
Why?
The main HCI101 bug of course is that there is no explanation on that page of what the green is supposed to mean. Presumably it took a lot longer to add and test (I hope!) the "feature" than it takes to write a single line of text at the top of the page documenting what it means. Having a mystery "feature" is worse than _not having it at all_, because the user has _no idea_ whether and how to react to it.

**Comment by adisandro** [comment]
From what I can see it's an attempt at validating the inserted data gone wrong.

When you input text, the mark can't be processed and it turns red: a database entry with a NULL grade is created
When you input a number, it turns green, except that it does it briefly and turns to white again. If you type something else, only then it turns green for good. In both cases, a database entry with the correct grade is created.
When you input a number followed by some text, only the number part is considered and it follows the previous rule.

**Comment by arkon** [comment]
On a side note, shouldn't the inputs only accept numbers then?

**Comment by adisandro** [comment]
Pull requests are always welcome :)

**Comment by gfbee** [comment]
Until there is documentation, and good evidence of proper testing, please turn of this **attempted** feature, and don't accept any pull requests that don't include user-visible documentation of changes, and a record of proper testing.
