### ISSUE TITLE
Overlay on dialog pop up

### ISSUE THREAD

**Issue by tagniam** [MarkUsProject/Markus#3212]
![screenshot at 2017-10-14 23 35 54](https://user-images.githubusercontent.com/6921736/31581395-b7054cec-b138-11e7-939b-f7873ead28dd.png)

Tested in Firefox. When I press the `Add New File` button, the dialog is overlayed by a div with class `lean-overlay` that prevents me from pressing any buttons on the dialog.

Weirdly enough this bug only occurs if I enable the [WOT](https://addons.mozilla.org/en-US/firefox/addon/wot-safe-browsing-tool/) extension.

I believe this is related to #1611.

**Comment by david-yz-liu** [comment]
Thanks for reporting this, @tagniam!
