### ISSUE TITLE
tool tip for student submission shows no files when there are!

### ISSUE THREAD

**Issue by jmzaleski** [MarkUsProject/Markus#3225]
<img width="1440" alt="screen-shot-busted-tooltip" src="https://user-images.githubusercontent.com/9355220/32115376-92d6dc38-bb14-11e7-911e-827139beefb6.png">

suke1 did submit files..

**Comment by adisandro** [comment]
Were those files submitted after the deadline?

**Comment by jmzaleski** [comment]
nope.. but the last revision was pretty darn close.

Mathew Zaleski
mobile: 647-223-6005 home: 416-778-8889
94 Hogarth Ave, Toronto, ON, M4K1K4
