### ISSUE TITLE
CSRF Vulnerability

### ISSUE THREAD

**Issue by peterzhu2118** [MarkUsProject/Markus#3237]
I believe MarkUs is vulnerable to CSRF. I am able to send POST requests through Postman without sending the CSRF token. This is caused by the fact that in the [ApplicationController](https://github.com/MarkUsProject/Markus/blob/master/app/controllers/application_controller.rb#L15) it uses `protect_from_forgery` rather than `protect_from_forgery with: :exception`. I believe this choice was to enable support API, however `protect_from_forgery with: :exception` can be enabled in the controllers that do not serve API requests.

Also odd on how the logout is a GET request instead of a POST request, which would not be protected against CSRF (if it was enabled).

**Comment by david-yz-liu** [comment]
Thanks @peterzhu2118!
