### ISSUE TITLE
Monitoring student absence

### ISSUE THREAD

**Issue by benjaminvialle** [MarkUsProject/Markus#325]
Our assignments in 1st and 2nd year are in class, during 4 hours. Students put their code at the end of the morning.

Some of our graders noticed that absenteeism was increasing due to the fact that MarkUs was available over the net, out of the School.

A little UI to « make the call » (i don't know if it is the right term) per assignment would be great ! I mean, graders assigned per sections could tick if each group/student is present and then, when correcting the assignment, see if the student was physically present or not during class.

We would have to make this configurable per assignments.

What do you think of that ?

**Comment by david-yz-liu** [comment]
Implemented a tagging feature in #1947.
