### ISSUE TITLE
High CPU usage on marking submission page

### ISSUE THREAD

**Issue by kamiyaa** [MarkUsProject/Markus#3260]
For loading certain submissions, the CPU usage spikes drastically.
To the point that Firefox cannot load the webpage and prompts user to kill webpage.
Google Chrome also spikes in CPU usage for a few seconds before being able to load the webpage.

Tested on:
- Linux-4.14.8
- Firefox-57.0.1
- Google-Chrome-63.0.3239.108
- Markus-1.6.0.DEV

If you need more information, feel free to ask and I'll try to provide them.

**Comment by adisandro** [comment]
Is this still happening?
We think this was related to a high number of annotations and fixed it in Markus 1.6.1

**Comment by kamiyaa** [comment]
Won't be able to test until UofT upgrades to 1.6.1.
When they do, I doubt I'll be able to reproduce the same environment as before.
So I'll just close this issue.
