### ISSUE TITLE
api: Download marks spreadsheets

### ISSUE THREAD

**Issue by colinmorris** [MarkUsProject/Markus#3278]
Looking at the [API docs](https://github.com/MarkUsProject/Markus/wiki/RESTfulApiDocumentation) it doesn't seem like there's a way to download or otherwise interact with marks spreadsheets. This would be a useful feature for me.

(I'm using Markus for a self-paced course with no deadlines, so our marks spreadsheets are basically in a state of constant flux.)

**Comment by adisandro** [comment]
Fixed by aad365e5cc83fa79e7ee32b03cbd5d1cf4d57b9e
