### ISSUE TITLE
Feature Request: Aggregated Instance Access

### ISSUE THREAD

**Issue by ansermino** [MarkUsProject/Markus#3319]
As a student it is very frustrating trying to hunt down the link to a specific instance. Far too often profs/lecturers forget to share the link, and come crunch time this can seriously hinder students. While it is possible to manipulate a known Markus URL to a desired one this not a user friendly solution. From what I understand by design class offerings on Markus are isolated from each other. Thus I propose one of the following:

- An aggregate view of courses for each student. This may not be feasible with the current application design, I am not familiar enough with it to say for certain

- A URL constructor tool. Allow students (and other users) to input the relevant fields to generate the desired URL. This would likely have to be institution specific.

**Comment by adisandro** [comment]
- You are right about the first point, MarkUs is designed to be a self-contained class for a course, not a portal for users. The aggregate view is not feasible.
- I don't understand what you're proposing in the second point. Mapping a website (in this case, MarkUs) to a url is not something that the website itself can control. It's a job for the sysadmins of the institution, they set up the web servers to serve MarkUs websites at certain urls. This is not something the MarkUs project can do anything about.

**Comment by ansermino** [comment]
What I'm proposing is a utility tool that would lie outside any specific instance but within an institution. At UofT for example the URL for an instance consists of the course code, year, and first month of the semester. As a user I would ideally like to navigate to markus.[instituition domain].com specify the required fields (coursecode, year, month) and be redirected to the correct URL (eg. markus.[institution domain].com/coursecode-year-month).

Perhaps this is something best left up to the institutions, but that does make me wonder -- why doesn't Markus has some sort of discovery service built into it? Does it rely solely on the URLs of instances to be manually shared by instructors?

**Comment by adisandro** [comment]
The teaching labs at St. George know about it, they'll think about setting up a landing page.
Closing.

**Comment by kshvmdn** [comment]
Looks like this is a thing now: https://markus.teach.cs.toronto.edu/. 😃
