### ISSUE TITLE
submission: Marking completeness indicator per individual marker

### ISSUE THREAD

**Issue by cchristodoulaki** [MarkUsProject/Markus#3322]
When marking assignments is rigidly split between multiple markers e.g., Person A responsible for q1-q3 and person B responsible for q4-q7 currently both need to complete their marking for an assignment marking to be labeled completed. 

Can you add an indicator of marking completeness per marker on each submission? e.g., marking completed by marker A but pending by marker B.

**Comment by adisandro** [comment]
@david-yz-liu this could be done with a new icon+tooltip text in the submission view.

**Comment by david-yz-liu** [comment]
@cchristodoulaki thanks for bringing this up! This is certainly a reasonable concern. @adisandro we can discuss this further.

**Comment by mishaschwartz** [comment]
Reason for marking as invalid:

- this information is available in the grader distribution graph on the Dashboard page
