### ISSUE TITLE
MathJax seems to be broken for multiple delimited statements

### ISSUE THREAD

**Issue by johntiger1** [MarkUsProject/Markus#3324]
![image](https://user-images.githubusercontent.com/14852840/38228753-3590ecc2-36d3-11e8-97ff-33a0088f257d.png)

Not sure if this is actually a bug or just my inexperience with MathJax, but when I have an annotation like 

```
Text $$delimited_statement$$ more text $$another_delimited statement$$
```

it comes out all wonky. Any help? I am fairly sure I didn't have this problem before (a month ago or so)

Thanks

**Comment by mishaschwartz** [comment]
This is related to an issue raised for MathJax: [Subscript notation issue #329](https://github.com/mathjax/MathJax/issues/329).

The solution seems to be to put a backslash before underscores between `$` delimiters.  

For example, in your case you should write your annotation as:
<img width="488" alt="screen shot 2018-04-03 at 11 42 05 am" src="https://user-images.githubusercontent.com/4380924/38259880-2ca60ee2-3734-11e8-8c12-d0ab5d3ca8f6.png">

**Comment by johntiger1** [comment]
Thanks!
