### ISSUE TITLE
incorrect totalling of mark

### ISSUE THREAD

**Issue by dmadras** [MarkUsProject/Markus#3352]
![screen shot 2018-04-23 at 11 36 19 am](https://user-images.githubusercontent.com/5509159/39137059-b3e777ea-46ea-11e8-8ef5-c2b87f15f57a.png)

Unsure exactly what the issue is ... but these marks don't add up to 13. I've re-entered the marks, clicked on and off the boxes, checked on the summaries page, and Markus insists the total mark is 13/30 (see top left corner of screenshot). Don't exactly know how to reproduce this, but thought it was worth mentioning.

**Comment by adisandro** [comment]
There could be an automatic deduction for late submission, in the summary tab. Did you check that?

**Comment by adisandro** [comment]
It is visible to tas, it's in the summary tab (the tab next to marks, not the summary page), at the bottom.
Closing this.
