### ISSUE TITLE
Student Numbers from MarkUs

### ISSUE THREAD

**Issue by jessebett** [MarkUsProject/Markus#3355]
Downloading detailed reports and marks sheets from MarkUs only provides the students' UTORIDs. 
This is unfortunate because submitting the final grades via CSV eMarks requires studetns' student numbers.

Is there a way for MarkUs to provide student numbers in the downloadable spreadsheets?

**Comment by partoo-vk** [comment]
claim

**Comment by partoo-vk** [comment]
claim

**Comment by partoo-vk** [comment]
What should I name the new column? is it "student number", or "id_number"...?
