### ISSUE TITLE
Show starter code repository URL on Assignment form

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#3362]
To be able to view this:

1. Create a new assignment.
2. The page will refresh to show a form for updating the assignment (this is under the "Settings" tab). At the very bottom of the page, there's a new section for the assignment's starter code. This is where the repository URL should go.

**Comment by partoo-vk** [comment]
Claim

**Comment by amrrsharaff** [comment]
I can work on this issue.
