### ISSUE TITLE
Grade Entry Form Editing as Admin

### ISSUE THREAD

**Issue by PkHutch** [MarkUsProject/Markus#3366]
The bug is minor but does slightly impede the smoothness of use.

When editing a mark spreadsheet as an admin, hitting the "Update Marks Spreadsheet" button twice in a row without any added columns will result in multiple error messages.

To reproduce, in a fresh development environment take the following steps:

1. Log in as administrator, the account used in this case was `a`
2. Edit one of the mark spreadsheets, the mark spreadsheet used in this case was `quiz1`
3. Delete all of the columns, do this by ticking the "Remove" box for all columns, there should be three, and then hit the button "Update Marks Spreadsheet"
4. There should now be a single column remaining, which you can then delete, or not.
5. If you decide to delete it and hit "Update Marks Spreadsheet" it will reappear, and you will be in the same scenario as if you decided to not delete it.
6. Now hit "Update Marks Spreadsheet" a second time and there will be a bunch of errors caused by the empty column.

I believe that if there when there are no columns we should not have an empty column be added to the page to avoid these errors for the user.

**Comment by david-yz-liu** [comment]
This will be addressed by fixing #3359.
