### ISSUE TITLE
Sanitize filename and convert file content to UTF-8 of uploaded files

### ISSUE THREAD

**Issue by jerboaa** [MarkUsProject/Markus#338]
We seem to have several problems related to bad filenames and messed up character encodings. I think it would be a good idea to implement the following:

 1. Filenames get sanitized: new_filename = old_filename.gsub(/[^a-zA-Z0-9\.\-_]/,'_') I.e. replace all characters which aren't ASCII-alphanumeric, dash, dot or underscore. I think we are doing this already. Maybe we need to spell things out more explicitly in order to avoid accents, etc. in filenames. I'm not sure how ruby's \w character class is defined nor if [a-z] would match an accented e.
 2. Convert the file content of uploaded files as they are uploaded to UTF-8 (at least make an attempt). I think we won't lose here, since we don't do any conversion at the moment and with the conversion in place we'd catch a few more encoding related errors.
 3. Make sure we update JavaScript code of the student's file-manager code in order to account for changed file sanitation.

For 2. we should probably use the cmess gem [1]. What do you think?

[1] http://prometheus.rubyforge.org/cmess/

**Comment by david-yz-liu** [comment]
(1) seems to work now. Closing until we hear a new complaint about file contents encoding.
