### ISSUE TITLE
Unwanted italics between underscores in annotations

### ISSUE THREAD

**Issue by AlexeyKhrabrov** [MarkUsProject/Markus#3415]
Parts of identifiers between underscores (e.g. "del_pid_sysc" as in the screenshot) in annotations are formatted as italics, in both "Source code" and "Annotation" tabs. This makes it impossible to search for such words in the "Annotations" tab, and can be confusing and ambiguous (and looks a bit annoying).

![screenshot](https://user-images.githubusercontent.com/9388553/41487848-41749ae2-70b8-11e8-8a6e-6dc0c2df8e98.png)

**Comment by mishaschwartz** [comment]
I'm unable to replicate your problem. Can you please let me know the exact Markdown/latex string you used to get that annotation.  So far I have tried:

- foo_bar_baz  ->  foo_bar_baz
- foo_bar_ baz ->  foo&zwj;_bar_ baz
- foo_bar_\&zwj;baz  ->  foo_bar_\&zwj;baz
- foo_bar_\&#xfeff;baz  ->  foo_bar_\&#xfeff;baz

Which indicates: 

- what I typed  -> what I saw

Note that \&zwj; and \&#xfeff; are a zero-width joiner and a zero-width no-break space respecitively

You can also try escaping your underscores and see if that helps:

- del\\_pid\\_sysc  ->  del_pid_sysc

**Comment by AlexeyKhrabrov** [comment]
For the screenshot, the string I entered was "already done in del_pid_sysc; the count is invalid now".

I'm using the current csc369-2018-05 MarkUs instance, in case this matters. I am currently able to reproduce the issue. It affects both inline annotations and the "overall comments" section.

As far as I understand, in Markdown, text between underscores should be rendered as italics only if the whole word is wrapped in underscores.
Example: foo_bar_baz vs. _foo_bar_baz_ (typed as "\_foo\_bar\_baz\_", so the GitHub Markdown editor behaves this way).

Escaping works, thanks.

**Comment by mishaschwartz** [comment]
Thanks for the details. As you point out, the markdown editor for the annotations does behave slightly differently from the one used by GitHub but since they actually use their own [dialect](https://github.github.com/gfm/) I don't think we can expect ours to behave exactly the same.  

For now, please continue to escape characters with slashes if you need them to be displayed as typed.
