### ISSUE TITLE
Running all migrations from scratch must rebuild schema.rb

### ISSUE THREAD

**Issue by benjaminvialle** [MarkUsProject/Markus#353]
While trying to rebuild db/schema.rb, some old migrations failed.

In order to keep MarkUs as clean as possible, we should have a the possiblity to rebuild schema.rb from scratch using only migrations. 

See http://pathfindersoftware.com/2008/07/resolved-should-schemarb-be-included-in-your-source-control/

It is not urgent. But it could be good to have this in 1.0.0

**Comment by david-yz-liu** [comment]
PostgreSQL is more or less standard now, unless we get complaints from someone.
