### ISSUE TITLE
Download and Upload csv/yml files are inconsistent

### ISSUE THREAD

**Issue by mishaschwartz** [MarkUsProject/Markus#3559]
In a lot of cases where there is both a download and upload option for some data (user table, submissions table, etc.) the format that is downloaded is inconsistent with the format that is required for the upload. 

For example, sometimes the column orders are swapped or columns are missing entirely as is the case in the user table. 

This makes it very difficult to download a csv, make a few changes minor changes and then upload the same file.

**Comment by mishaschwartz** [comment]
From email correspondence:

> Under settings/marking scheme the upload yml gags if the description is
> delimited by single quote characters.  However, if you download a description
> created through the GUI it shows single quote characters.

**Comment by david-yz-liu** [comment]
This should be fixed now.
