### ISSUE TITLE
spreadsheet: Entering marks on chrome issues

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#3567]
On Chrome (Version 69.0.3497.100 (Official Build) (64-bit)) on MacOS (10.13.6), when I enter a number in a field, the number disappears immediately, but the total is correct.  In the image below I have entered a 1 in the bottom left box, so the total on the right is correct, but I only see the 1 when I refresh the page.

![markus-spreadsheetbug](https://user-images.githubusercontent.com/420794/45918084-8eaa0100-be4f-11e8-8077-a24768f8d609.jpeg)

I just noticed that if I enter a 0 is does stay even after I delete it.

**Comment by adisandro** [comment]
This was fixed by #3582
