### ISSUE TITLE
spreadsheet: link problem

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#3568]
In the dashboard, I click on a Marks Spreadsheets spreadsheet, and then click on the spreadsheet link at the top of the graph, the route is ` /grade_entry_forms/1/view_summary ` which goes to a blank page.

(From the Assignments tab, the route is ` /grade_entry_forms/1/edit `)

**Comment by adisandro** [comment]
Thank you for reporting it @reidka!
