### ISSUE TITLE
Shortcuts?

### ISSUE THREAD

**Issue by zalsader** [MarkUsProject/Markus#3570]
Are there shortcuts to change Marking Status, or move to next submission? This is helpful for speed marking. Thanks!

**Comment by adisandro** [comment]
There are, they're just extremely hidden for some reason.
If you press '?' on your keyboard, you can see the list of allowed shortcuts.

**Comment by mc256** [comment]
Is it possible to add more keyboard shortcuts?
I am not sure how to contribute to this project.
