### ISSUE TITLE
Markus time-out when uploading large file on slow connection

### ISSUE THREAD

**Issue by johntiger1** [MarkUsProject/Markus#3581]
I can reliably cause the following error screen from my parents' home connection. I am trying to upload a 1.5 MB file on ~1mb/s up connection; if I switch to my phone's hotspot the error message goes away.  

![2018-09-27 2](https://user-images.githubusercontent.com/14852840/46185758-5ec48880-c2a9-11e8-83ab-1fb9ba90a745.png)

**Comment by johntiger1** [comment]
Hi @adisandro thanks for the reply, yes it did take more than 20 or 30s! Is there any way around this?

**Comment by mishaschwartz** [comment]
Closing because over a year old.

For future reference, the only other way to upload files is to upload them via the version control backend (either svn or git depending on your course).
