### ISSUE TITLE
Modal window for large annotations goes off screen

### ISSUE THREAD

**Issue by wlgranados** [MarkUsProject/Markus#3594]
When you create a really long annotation, the buttons: "create new annotation" and "cancel" go off screen, making it not possible to submit the annotation through UI.  I think this is because of the bookmark bar, below you can see two similar examples, where the buttons are barely viewable.

See below:
<img width="1278" alt="screen shot 2018-10-04 at 5 17 00 pm" src="https://user-images.githubusercontent.com/5634714/46503804-f5d59700-c7f9-11e8-9b77-864edbc736a3.png">

<img width="1279" alt="screen shot 2018-10-04 at 5 25 30 pm" src="https://user-images.githubusercontent.com/5634714/46504003-a17ee700-c7fa-11e8-9913-5823d7262ded.png">

**Comment by mishaschwartz** [comment]
@wlgranados Thank you for reporting this.  We are planning on a full rewrite of our modals so I will make a note of this issue and make sure that modal size scales to the browser size when we do the rewrite.  

For now, zooming out on your browser should make the modal smaller, allowing you to click the submit buttons.  I notice you are using a Chrome browser so you should be able to zoom out with `'ctrl'`+`'-'` (or `'cmd'`+`'-'` on a mac)
