### ISSUE TITLE
Annotation removes code from a line

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#3639]
![syntax-highlightbug](https://user-images.githubusercontent.com/420794/47271157-d2be1d80-d543-11e8-818a-7279e1d03254.jpeg)

Line 150 is longer in the student's submission.  I selected most of the text on this line and then added an annotation.  The annotation doesn't show, but also the text I annotated disappeared.

**Comment by mishaschwartz** [comment]
I'm still unable to recreate this bug so I'm going to close this for now. If this continues to happen, please re-open this issue.
