### ISSUE TITLE
Hide Average Spreadsheet Mark from Students

### ISSUE THREAD

**Issue by jessebett** [MarkUsProject/Markus#3840]
I was not aware of this until I changed my view to a student's account that MarkUs reports the average mark from the spreadsheet to the students? Is there any way to disable this?

As I bring up in #3839 and #3833, there appears to be no way to ignore inactive students from the Marks Spreadsheet statistics. Since this very incorrect statistic was being reported to my students I received a few emails asking about midterm reweighing, as MarkUs was indicating to them that the midterm average was almost 30% lower than the true average.

Of course, this in particular wouldn't be an issue if there was any way to remove inactive students from the statistics (or to stop counting No Marks as 0s). If there's no way to hide the marks average, even if it is correct, is this because there's no legitimate reason to not provide that for students?

**Comment by mishaschwartz** [comment]
Reason for marking as invalid:

- with the addition of the grades summary view for students it seems we are going down the route of providing more stats to students not fewer
- as long as inactive students are not reported (or more importantly, unreleased results are not reported) then I believe assignment stats should not be hidden
