### ISSUE TITLE
Annotations on src files do not show up sometimes until page refresh

### ISSUE THREAD

**Issue by seanygg** [MarkUsProject/Markus#3891]
Annotations added to source files will not show up sometimes (on the annotations list, or as yellow highlight over the code) until the page is refreshed

**Comment by mishaschwartz** [comment]
Hi @seanygg, thank you for reporting this. 

Can you please provide us with a few more details about this bug:

- Does this occur for text, pdf, and/or image annotations?
- When specifically does this occur? (The first time you visit the page after logging in? Every time you navigate to a new page?)
- Which browser are you using? Does this error occur with multiple browsers?
- Is there any other information that would help us recreate this issue?

Thanks,

Misha

**Comment by mishaschwartz** [comment]
Closing because 1 year old. 
Please re-open with more information to help recreate the issue if this issue persists.
