### ISSUE TITLE
Student Interface "Your Term Marks" Allows you to 'Sort'

### ISSUE THREAD

**Issue by Tom-Hayes** [MarkUsProject/Markus#4075]
On the student interface of MarkUs, the "Your Term Marks" section gives the student the option of searching by User Name, First Name or Last Name (see image):  
![Your term marks student interface](https://user-images.githubusercontent.com/50387112/61486542-b2f04480-a971-11e9-9091-6aa26596d524.png)  
I believe this feature is useless to students as they'll only see themselves and no one else in this section. Perhaps this first row can be removed in the student view?

**Comment by ignaspa** [comment]
Resolved in [PR #4740](https://github.com/MarkUsProject/Markus/pull/4740)
