### ISSUE TITLE
Broken links in wiki (User Guide, Grader Guide, user stories)

### ISSUE THREAD

**Issue by colinmorris** [MarkUsProject/Markus#4287]
At the top of the [wiki](https://github.com/MarkUsProject/Markus/wiki) the "User Guide", "Instructor Guide", "Grader Guide", and "Sandbox" links are broken. (The link to the ["newer version of the Instructor Guide"](https://github.com/MarkUsProject/Markus/wiki/Instructor-Guide:-Homepage) a little further down does work though.)

Also, all of the links under the "User Roles and Stories for MarkUs" bullet in [this section](https://github.com/MarkUsProject/Markus/wiki#everything-a-developer-needs-to-know-about-ruby-ruby-on-rails-and-markus) seem to be broken.

I'm assuming these links used to work, but the content they refer to has moved? Or if that's not the case and these just represent future work, maybe they could be annotated with [todo] or something so readers won't be disappointed when they try to follow the links and find nothing? It's unfortunate the GitHub wiki system doesn't follow a Wikipedia-like convention of styling links to non-existent pages with a different colour.

**Comment by david-yz-liu** [comment]
Thanks for pointing this out! I've been meaning to update that page for a while but haven't had time. It's been updated now, with a bunch of old links removed (and correct links added when possible).
