### ISSUE TITLE
Integrate annotations and criteria

### ISSUE THREAD

**Issue by mishaschwartz** [MarkUsProject/Markus#4288]
- allow certain annotations to automatically update the mark for a given criteria if that annotation is used to mark an assignment.

context from email correspondence:

> To give you some context first, currently my TAs grade code by adding
> annotations which include a comment about the mistake and the number of
> marks deducted. In some cases, the number of marks mentioned in the
> annotation is 0 if it's a minor mistake, or it could be a bonus mark (in
> rare cases where something exceptional deserves recognition). Then the TA
> adds the deductions in the rubric on the right pane, or in the extra marks
> section (for bonuses). So there are basically two steps that the TA takes
> (annotation comment, then marks updated in the rubric by manually
> aggregating all deductions from the annotations). I think these steps could
> be combined by having in each annotation a dedicated field where the TA can
> enter a number of points (negative if it's deduction, or 0, or positive if
> it's a bonus), which would be applied automatically in the rubric. So
> instead of stating in the annotation string "Incorrect use of X (-5
> marks)", there would be a separate field to enter the "-5" in it, and a
> grading criteria dropdown list perhaps, which would automatically update
> the rubric in the right pane once the annotation is entered.
>
> The reason I'm asking this is because currently when an annotation comment
> is unclear, we can update the annotation string and it will propagate that
> through all assignments that have the same annotation. That cannot be
> automatically done about the marks being deducted. So if a TA makes a
> mistake and deducts, say 5 marks, instead of 2 marks for some student
> mistake, then we currently have to go through all submissions and manually
> fix the marks in the rubric wherever we see that same annotation. If the
> marks deducted would be associated with the annotation, we could adjust the
> TA's mistake in one single step. Sometimes it may not even be a TA mistake,
> we might just want to adjust the weight of some deduction for all
> submissions because, for instance, all students interpreted something
> differently than intended.

**Comment by david-yz-liu** [comment]
Resolved by #4693.
