### ISSUE TITLE
In submissions view, pdf previews randomly disappear in Chrome

### ISSUE THREAD

**Issue by colinmorris** [MarkUsProject/Markus#4357]
I can currently reproduce this by hovering over one of the annotation categories that appears above the pdf preview. When I do this, the embedded pdf preview is 'blanked out', replaced by a void of white. The toolbar with page and zoom controls still appears, and in fact I can consistently cause the pdf preview to reappear by hovering on any of the buttons in that toolbar (e.g. the refresh button, or the + and - buttons).

It (the disappearing phenomenon) also seems to happen stochastically when I'm doing other things. I've even seen it happen when I wasn't touching the mouse or keyboard. It happens frequently enough to be very disruptive (more than once a minute).

I've tried two different machines (a desktop running Chrome for linux, and a laptop running ChromeOS) and both have had this issue on Chrome. When I switched to Firefox, the issue did not occur.

I don't think it's an extension issue, as I can still reproduce it in a private browsing tab.

I don't see any console messages when this occurs.

**Comment by mishaschwartz** [comment]
Thanks for reporting this. There is some spooky interaction going on with the library we are using to render PDFs and chrome. We've been investigating this but as of this moment I haven't pinpointed a specific cause.

I'll make sure to update this ticket in the future when I'm able to find something.

The best workaround in the meantime is, as you pointed out, to use Firefox when grading pdfs on MarkUs.
