### ISSUE TITLE
Certain fonts not rendering in pdf preview

### ISSUE THREAD

**Issue by colinmorris** [MarkUsProject/Markus#4386]
Documents rendered from .tex files which use the default font show up fine.

But for documents that `\usepackage{ccfonts}`, most of the text is invisible in the preview.

I was also able to find one other document which didn't use this package, but which had rendering issues. Lines from the preamble which are plausible culprits in this case:

```
\usepackage[T1]{fontenc}  
\usepackage[latin9]{inputenc}  
\usepackage{amsfonts}
```
(In that example, the math mode content renders fine, but all the prose is invisible.)

[Here's an example of a pdf](http://www.cs.toronto.edu/~colin/236/W20/assignments/a1_solutions.pdf) that should reproduce this issue. (Only the boldface text like "Solution:" and "Inductive Step" show up on MarkUs.)

Reproduces on Linux in Chrome and Firefox and in Chrome for Android.

**Comment by mishaschwartz** [comment]
Fixed with #4382
