### ISSUE TITLE
Zip files from "Download submissions" contain paths that conflict with filename of zip archive

### ISSUE THREAD

**Issue by colinmorris** [MarkUsProject/Markus#4468]
In the submissions list, if I select some submissions and click the "Download submissions" button, I get a zip file with a name like `<assignmentid>_<username>.zip`. The contents of this zip includes a directory that is also named `<assignmentid>_<username>.zip`. This means that unzipping the archive leads to an error, unless I rename the zip file first. e.g.

```
$ unzip q11_colin.zip 
Archive:  q11_colin.zip
checkdir error:  q11_colin.zip exists but is not directory
                 unable to process q11_colin.zip/<studentid>/.gitkeep.
checkdir error:  q11_colin.zip exists but is not directory
...
```

**Comment by david-yz-liu** [comment]
Thanks for reporting! Fixed in #4463.
