### ISSUE TITLE
in submission view, pdfs containing large images run over footer

### ISSUE THREAD

**Issue by colinmorris** [MarkUsProject/Markus#4495]
See screenshot below. Far from a big deal, it just looks a little awkward, and blocks the footer (including the "Github issues list" link - my favourite part of the interface!)

Seems to be limited to pdfs with large embedded images

![markus_pdf_overflow_](https://user-images.githubusercontent.com/695907/78281961-85d8c780-74e9-11ea-826f-00939bae93a9.png)

**Comment by david-yz-liu** [comment]
Thanks for reporting this, fix should be in soon!
