### ISSUE TITLE
Rescaling max marks of a rubric criterion causes it to sometimes appear unset in submission view

### ISSUE THREAD

**Issue by colinmorris** [MarkUsProject/Markus#4514]
After an assignment had been fully graded, I edited some criteria to change their maximum marks. It seems that, for rubric criteria, if a submission's score for that criterion becomes a non-integer, then in the submission view, the score for that criteria becomes hidden.

See the screenshot below for an example. The second and third criteria were scaled to be out of 3. This submission earned the "Good" level, for a score of 2.25/3. But this is not apparent. 

![markus_rescaled_criteria](https://user-images.githubusercontent.com/695907/78613115-f6108180-7838-11ea-8154-3da63b56930c.png)

If I click the criterion to try to expand it, it looks like this:

![markus_criteria_expanded](https://user-images.githubusercontent.com/695907/78613204-35d76900-7839-11ea-827d-70c146d7d525.png)

The only way to see the actual mark for this criterion is to go to the summary view:

![markus_rescaled_criteria_summary](https://user-images.githubusercontent.com/695907/78613286-65867100-7839-11ea-9880-ca10b1bf2fbd.png)

(I'm not sure if the rescaling is a necessary part of reproducing this. It might also happen if a rubric criterion is created to be out of 3 from the beginning.)

**Comment by mishaschwartz** [comment]
We're currently in the process of updating the rubric criteria code entirely. I'll check back on this once the sti-criteria project branch has been fully merged into master.
