### ISSUE TITLE
When I quickly type "0.5" into into a flexible marking item, MarkUs turns it into 05.

### ISSUE THREAD

**Issue by falsifian** [MarkUsProject/Markus#4518]
I'm using Firefox 74.0.1 (64-bit) on Linux.

I'm grading an assignment with one flexible criteria out of one.

Sometimes I enter a grade of 0.5. But if I type that quickly, MarkUs ends up putting 05 in the field and then the background becomes read (because 5 > 1, I guess).

The issue appears to be that if I quickly type "0.", MarkUs replaces it with "0".

If I pause briefly between the "0" and the ".", the problem doesn't happen.

It's not a big deal in my case, since MarkUs flags the error, but I wonder if there's potential for data misentry if the item isn't actually out of 1 and someone doesn't notice they've written 5 instead of 0.5.

**Comment by falsifian** [comment]
There's a similar problem when deleting:

* Start out with a mark of 5.1.
* Put the cursor after the one, and type backspace twice, to turn it into 5.
* You end up with an empty field instead of 5, because the "." got deleted along with the 1.

**Comment by david-yz-liu** [comment]
Thanks for reporting this, fix should be in soon!
