### ISSUE TITLE
Feature request: rotate photos (manually or based on exif)

### ISSUE THREAD

**Issue by falsifian** [MarkUsProject/Markus#4530]
I'm grading some photo submissions for a quiz. Often I find that the photos appear sideways in MarkUs.

In the cases I've seen so far, the EXIF metadata already includes the correct orientation, so I've been able to turn them into a usable pdf with a command like `convert -auto-orient quiz10.jpg 00_processed.pdf` (using `convert` from ImageMagick).

(Related FR: #4455 requests zoom in/out.)

**Comment by david-yz-liu** [comment]
Hi @falsifian, we're working on reproducing this one. Do you happen to still have the file you downloaded (`quiz10.jpg`), and if so, can you send it to me (david@cs)? Thanks!

**Comment by falsifian** [comment]
@david-yz-liu, I sent you a different file because I don't remember which student `quiz10.jpg` was from. (I sent it from falsifian@falsifian.org. Please let me know if it ends up in spam; it's a new email address that I'm managing directly.)

A few notes:

* If I open the file with Gnome image viewer or directly in Firefox, it is oriented correctly. (I don't remember whether this was true for the original `quiz10.jpg`.)
* However, in MarkUs, it appears sideways. It also appears sideways if I convert it to pdf using `convert 20200324_211645.jpg processed_.pdf` (`convert` from ImageMagick).
* If I add the `-auto-orient` to the ImageMagick `convert` command, the pdf is oriented correctly.
* Hypothesis: the image has exif metadata about its orientation which needs to be taken into account in order to show it correctly.

**Comment by falsifian** [comment]
MarkUs url, if you have access: https://markus.teach.cs.toronto.edu/csc240-2020-01/assignments/16/submissions/2431/results/2431/edit

(You might have to choose the jpg from the file dropdown.)
