### ISSUE TITLE
Spurious "missing host to link to" error on releasing grades

### ISSUE THREAD

**Issue by dijkstracula** [MarkUsProject/Markus#4599]
I observed the following error when releasing my grades:

![image](https://user-images.githubusercontent.com/8949748/82403546-55f36e00-9a1c-11ea-8d43-eabdefdfb326.png)

Since I don't want to un-release my grades in the spirit of filing an issue, I'm not 100% sure of the repro steps, but, what I recall doing is:

1) selecting "complete" from the marking state dropdown
2) selecting all submissions
3) selecting "release grades"

Curiously, even though the error alert pops up, the marks do seem to be released.

**Comment by mishaschwartz** [comment]
This sounds like a setup issue. Specifically, a configuration issue for ActionMailer. If anyone encounters this behaviour contact your sysadmin and ask them to double check the ActionMailer settings in `config/environments/production.rb`. 

For reference: 

https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
