### ISSUE TITLE
Can't specify required files while creating new assignment

### ISSUE THREAD

**Issue by dijkstracula** [MarkUsProject/Markus#4613]
When creating a new assignment, I filled out the properties portion, along with the "required files", "late submission policy", and "remark requests" portion.  When I click Save, I get

`ex4 could not be created due to the following error(s): Assignment files assignment must exist; Required files is invalid.`

In order to set required files, I need to delete the required files, hit save so the assignment is created, and then add them afterwards.

**Comment by mishaschwartz** [comment]
- resolved by #4551
- fixed in production as of v1.9.3
