### ISSUE TITLE
Frontend issues for STI-Criteria Branch

### ISSUE THREAD

**Issue by ashih2018** [MarkUsProject/Markus#4788]
The following issues are occurring in #4749 

1. When a student logs into their account past their submission date this alert pops up.
![image](https://user-images.githubusercontent.com/46202699/89491773-fe90ae80-d77d-11ea-96aa-dc6a134647a2.png)
![image](https://user-images.githubusercontent.com/46202699/89491780-05b7bc80-d77e-11ea-825d-44192938d113.png)
    - This appears at the bottom but I'm not sure whether it is related
        - ![image](https://user-images.githubusercontent.com/46202699/89491804-11a37e80-d77e-11ea-9eb7-8da3a1d94ed7.png)

2. Right now, the `updateMark` function in `result.jsx` is not being passed in `criterion_id` and `mark` correctly
    - This function has its parameters passed in from a call from `this.props.updateMark` in `marks_panel.jsx`. When this gets called from each individual `CriterionInput`, the `props.id` are assigned correctly as can be seen from inspecting the elements of the page and seeing that their ids of the HTML elements have their corresponding ids of the criterion.
    - When we send the request to `Routes.update_mark_assignment_submission_result_path` which calls `update_mark` in `results_controller.rb`, we get `params[:criterion_id]` set to the criterion name and `params[:mark]` set to the criterion id. Because of this, an error gets raised in this controller function as `result_mark` is not created properly and will not have a corresponding criterion when created.
    - This means that somewhere between calling `this.props.updateMark` in each individual `CriterionInput` and sending the ajax request to call the `update_mark` function in `results_controller` the `criterion_id` and `mark` data gets changed as it is what we want it to be within the `CriterionInput` components.

3. In the results panel, if you open up the console, these errors are appearing about `SubmissionSelector`
    - ![image](https://user-images.githubusercontent.com/46202699/89492822-811a6d80-d780-11ea-8f61-d6d933755a61.png)

**Comment by david-yz-liu** [comment]
Thanks @ashih2018. I think the second part is fixed, the first and third parts will be fixed soon, so I'm going to close this for now.
