### ISSUE TITLE
possible validation issue when marshalling data between Automated Testing page & autotester

### ISSUE THREAD

**Issue by dijkstracula** [MarkUsProject/Markus#4823]
I'm setting up an autograder test suite and upon saving I get the following error:

```
Traceback (most recent call last):
File "/data/markus/software/markus-autotesting-1.9.0/venv/bin/markus_autotester", line 11, in
load_entry_point('markus-autotester', 'console_scripts', 'markus_autotester')()
File "/data/markus/software/markus-autotesting-1.9.0/src/autotester/cli.py", line 257, in cli
COMMANDS[args.command](**kwargs)
File "/data/markus/software/markus-autotesting-1.9.0/src/autotester/cli.py", line 98, in wrapper
return func(*args, **kwargs)
File "/data/markus/software/markus-autotesting-1.9.0/src/autotester/cli.py", line 164, in update_specs
raise error
jsonschema.exceptions.ValidationError: {'test_suite_name': 'Q1', 'script_file': 'parta_tests.rkt'} is not of type 'string'

Failed validating 'type' in schema[0]['properties']['test_data']['items']['properties']['script_files']['items']:
{'enum': ['parta_tests.rkt', 'partc_tests.rkt', 'partb_tests.rkt'],
'type': 'string'}

On instance['test_data'][0]['script_files'][0]:
{'script_file': 'parta_tests.rkt', 'test_suite_name': 'Q1'}
```

As a user, I'm not exactly sure how to parse this error, but my impression is that it's expecting one of `['parta_tests.rkt', 'partc_tests.rkt', 'partb_tests.rkt']` but instead was passed a dctionary containing the script filename but also the test suite name.  Seems like this is all internal to Markus; I populate these fields from the GUI and don't have any control about the underlying type.

If so, was a change in either MarkUs or autograder perhaps not applied to the other?

**Comment by mishaschwartz** [comment]
The error message is generated by a dependency and it looks like they have some bug that reports errors from the wrong part of the form. The actual issue is that you need to select a category (admin or student) for your Q10 group.

**Comment by mishaschwartz** [comment]
To be honest, I just looked through the page and looked for missing values in inputs.
