### ISSUE TITLE
Enable subdirectory creation for students and set limits based on required files

### ISSUE THREAD

**Issue by mishaschwartz** [MarkUsProject/Markus#4912]
Right now if you have:
-  required files is enabled in subdirectories (enabled in #4903)
- "only required files" is enabled
- subdirectories are not created in starter files OR if a student deletes a subdirectory

then students will not be able to create new subdirectories and will subsequently not be able to submit required files.

We should:

- allow students to create subdirectories thought the UI.
- if there are required files, students can create subdirectories that are required to fulfill the required files (ie. if `sub1/sub2/test.py` is required then students can create `sub1/` and `sub1/sub2`)
- if there are required files, the code checks the content of an expanded zip file, not the zip file itself for the required files.

**Comment by david-yz-liu** [comment]
Closed in #5763.
