### ISSUE TITLE
Syntax highlighting for cpp files

### ISSUE THREAD

**Issue by kyokeunpark** [MarkUsProject/Markus#4965]
I noticed that I rely on syntax highlighting a lot more than I have initially thought. It has become quite difficult for me to mark .cpp files because of it.

Both .c and .h files have syntax highlighting which .cpp files can also take advantage of, so I do not think this would be too hard to implement. If someone could point me to the right direction, I would not mind trying to implement this myself as well and creating a PR.

Thank you.

**Comment by david-yz-liu** [comment]
Hi, we can add basic syntax highlighting for .cpp files using the existing C syntax highlighter using the same change as #4174. This won't support syntax highlighting for C++ specific syntax, though.

Also I'm not sure we can get this in for your marking for this semester, but you are certainly welcome to make a PR!

**Comment by david-yz-liu** [comment]
Fixed in #4965.
