### ISSUE TITLE
Sorting Collected Submissions by Submission Date

### ISSUE THREAD

**Issue by nisarg89** [MarkUsProject/Markus#4995]
Sorting collected submissions to an assignment by submission date doesn't seem to be working as expected. The attached image shows the result after clicking the "Submission Date" column (hence it has the black rectangle around it). Clearly, these are not sorted. 

In addition to the issue shown in the image, I would expect submissions with an empty submission date (when the group did not submit anything) to be grouped together, but that does not happen either.
![Capture](https://user-images.githubusercontent.com/4582395/100368125-2e83ec00-2fd1-11eb-9bca-ba6bd5bda7af.JPG)

**Comment by mishaschwartz** [comment]
empty submission date grouping issue has been resolved by #4921
