### ISSUE TITLE
Feature request: submit url

### ISSUE THREAD

**Issue by alecjacobson** [MarkUsProject/Markus#5014]
In addition to uploading files, for certain assignments I'd love if students can enter a url to a webpage/file.

Ideally, markus would do fancy things like validate that the inputted string is a proper url and maybe even allow me to restrict which domains are acceptable.

**Comment by mishaschwartz** [comment]
Right now, students can definitely upload a text file that contains a URL. Graders can then visit the url when marking the assignment.

The fancy url checking and domain restrictions could be implemented as well in the future as well.
