### ISSUE TITLE
Reviewing all uses of an annotation

### ISSUE THREAD

**Issue by dianehorton** [MarkUsProject/Markus#5026]
Currently, the Annotations tab shows the number of uses of any annotation.  It would be very helpful if we could get a view that gives us the subset of the submissions that used that annotation.  Even a list of group numbers would be great.

Use case: You are using deductive annotations, and TAs are in the middle of marking. You realize you need to change the way they've been grading, but don't have enough TA time to have them review every graded submission.  Almost always the use of a particular annotation indicates which ones need review.  This actually is relevant to rubric marking also.

Diane

**Comment by mishaschwartz** [comment]
Hi, I'm pretty sure the "Usage Details" table will show you the info you're looking for. It can be accessed by clicking the "Usage Details" button below each annotation definition.

<img width="727" alt="Screen Shot 2020-12-16 at 4 55 23 PM" src="https://user-images.githubusercontent.com/4380924/102411591-27447280-3fc0-11eb-8c91-faf0086c5c02.png">
