### ISSUE TITLE
"Download" button for starter files persists when it shouldn't

### ISSUE THREAD

**Issue by mariobadr** [MarkUsProject/Markus#5079]
Scenario: Upload a starter file to MarkUs for an assignment, then remove the starter file group.

Problem: After deleting all starter file groups for an assignment, MarkUs will still present students with the button to download the starter files. The result is an empty (I think) zip file (see attached).

[a1-starter-files-aaamario.zip](https://github.com/MarkUsProject/Markus/files/5851975/a1-starter-files-aaamario.zip)

I was able to reproduce this in my mbadrtest MarkUs instance. See assignments mariotest (no issues) vs. mariotest2 (has the problem outlined above).

**Comment by mishaschwartz** [comment]
resolved by #5160
