### ISSUE TITLE
Make Student Submissions View and Grader View Identical

### ISSUE THREAD

**Issue by mariobadr** [MarkUsProject/Markus#5124]
The Grader View conveniently shows unicode characters that are causing errors in a student submission:

![image](https://user-images.githubusercontent.com/5625409/107668400-a2dc3c00-6c5e-11eb-9c9a-8155f38c4e97.png)

It would be nice if the student submission view was the same. This way, students can find the invalid unicode characters in their code through MarkUs. Currently it shows this:

![image](https://user-images.githubusercontent.com/5625409/107668482-bab3c000-6c5e-11eb-8476-fff11c7f5b8e.png)

**Comment by mishaschwartz** [comment]
resolved by #5156
