### ISSUE TITLE
Late penalty deductions for file deletion

### ISSUE THREAD

**Issue by hhc97** [MarkUsProject/Markus#5129]
It seems like if a file is deleted on the web interface or through a push after the deadline for some assignment on MarkUs, a late penalty is applied.

However, this really should not be the default behavior, as you'd expect to be able to delete part of your submission without incurring a late penalty, as you are removing part of your submission, not adding to it.

Fix: use the submission time of the latest changed file currently present in the repo to calculate late penalties and deductions.

**Comment by mishaschwartz** [comment]
We discussed this for a while and I think that we actually do want to count deletions when calculating late penalties.
Consider the following scenario:

- an instructor requests that only specific files be submitted as part of an assignment, a student realizes after the deadline that they submitted an extra file and goes to delete it. The instructor will not be able to see that they should deduct marks from the student for not following directions.

If a student does delete a file after the deadline that truly does not make a difference to the grade, they should have a conversation with their instructor and it will be up to the instructor to decide how to handle it. Instructors always have the discretion to wave penalties and MarkUs should not make that decision for the instructor.
