### ISSUE TITLE
Feature request: View assigned student starter files when grading

### ISSUE THREAD

**Issue by bobthefairycat** [MarkUsProject/Markus#5137]
The new timed assessment feature works smoothly! Allowing students to submit a separate .pdf of their solutions to a written timed assessment, we no longer know what question they were answering.

As grading will depend on what starter files the student was assigned, it would be nice to have some way to easily retrieve or view the starter file(s) they were assigned while grading.

**Comment by mishaschwartz** [comment]
Please see the wiki page here:

https://github.com/MarkUsProject/Markus/wiki/Instructor-Guide--Assignments--Starter-Files#see-assigned-starter-files
