### ISSUE TITLE
Feature request: filters in grading view

### ISSUE THREAD

**Issue by bobthefairycat** [MarkUsProject/Markus#5167]
This would be a nice-to-have, for coordinating multiple graders:

- Having the option to skip to the next _ungraded_ student booklet, rather than the next alphabetically; within a specified criteria or tag (e.g. for a grader who is grading Q1, they would always get the next ungraded Q1). 
- Potentially also the ability to skip to view the next student booklet in asc/desc order of their grade (either aggregate for the whole assessment, or within a specified criteria). This is helpful for doing sanity checks on submissions & grading.

**Comment by david-yz-liu** [comment]
Thank you! We have implemented filters in #6642 and #6669.
