### ISSUE TITLE
problems with the classwide grade summary

### ISSUE THREAD

**Issue by dianehorton** [MarkUsProject/Markus#5180]
My classwide grade summary has many columns, with the result that I can't see the full column titles or out-ofs.  Changing the column width is very laggy in my large class, and also results in columns that do not line up at all.  I find it unusable.  Shrinking the whole thing (with command-minus) also messes up alignment.  One improvement that _might_ be easier than directly addressing these issues: Allowing the user to hover over the column title and see its content expanded.

I tried downloading the class summary, but the csv file doesn't show the out-of values.  This might be easy to fix.

**Comment by mishaschwartz** [comment]
related to #5179

**Comment by david-yz-liu** [comment]
The problem of resizing columns was fixed in #5288, and we've added an "Out of" column in the exported file in #5349.
