### ISSUE TITLE
Feature Request: Display to students when they started their timed assessment

### ISSUE THREAD

**Issue by pscience** [MarkUsProject/Markus#5187]
The UI for students doesn't tell them the time when they begin a timed assessment, leaving students to keep track of it on their own (and sometimes inaccurately so). It would be helpful if it could be displayed to them the exact time when students begin their timed assessments so they can plan accordingly.

**Comment by mishaschwartz** [comment]
The Assignment page on the student UI displays the following information on the Timed Assessment panel (left side panel)

> This assessment is due before Wednesday, July 07, 2021, 12:26:55 PM EDT without penalty.
> (started Wednesday, July 07, 2021, 10:26:55 AM EDT).

(The dates and times above are given as an example)

If this information is not sufficient, please feel free to suggest an alternative and we can re-open this issue.

**Comment by pscience** [comment]
Thank you @mishaschwartz for the reply. Perhaps this is only an issue with assessments that are over -- I may need help to verify if this is also an issue for timed assessments when they are in progress. For timed assessments that are over, e.g. a 2-hour test that can be taken any time over the course of a window between 9am and 5pm, after the test is complete, the student's view seems to display this (as an example):

> **Timed Assessment**
> You may start this timed assessment after: Monday, July 12, 2021, 09:00:00 AM EST
> You must start this timed assessment before: Monday, July 12, 2021, 05:00:00 PM EST
> This timed assessment is now over.
> Duration: 2 hours, 0 minutes
> 
> **Late submission policy**
> Due date including maximum late penalty: Monday, July 12, 2021, 05:11:28 PM EST
> A deduction of 0.0% will be applied every 0.17 hours up to 0.17 hours after the assignment is due.
> Thereafter, a deduction of 10.0% will be applied every 0.017 hours up to a maximum of 0.17 hours.

Nowhere on the panel do I see the UI telling the student that they had chosen to begin their assessment at Monday, July 12, 2021, 02:51:04 PM EST. However, the instructor's view can see this from the 'Submissions' tab of the corresponding assessment. If the student's view can also have this information, that would be helpful for allowing them to verify that they didn't go over time.

**Comment by mishaschwartz** [comment]
Ok I see what you mean. You are right that after the assessment is over, the student no longer sees the information about when they started. 

I suggest we keep the text the same but add the line that says:

> (started Wednesday, July 12, 2021, 10:26:55 AM EST).

under the "Timed Assessment" heading even after the assessment is over. And if they didn't start at all something like:

> (this assessment was not started).

What do you think about that?

**Comment by pscience** [comment]
I appreciate your confirming. Sounds great to me. Thank you!
