### ISSUE TITLE
Grading view "next" does not reload "test results"

### ISSUE THREAD

**Issue by bobthefairycat** [MarkUsProject/Markus#5399]
While grading, if reviewing the "test results" tab, clicking "next" does not load the next student's test results (instead, it stays at whatever the last loaded student's test results are). In case it matters, groups are set:

![image](https://user-images.githubusercontent.com/9201834/125344753-ac5cf380-e325-11eb-9f91-705ad42ed589.png)

**Comment by bobthefairycat** [comment]
Wow, that was fast! Thanks :)

**Comment by david-yz-liu** [comment]
No problem! We'll aim to update the live versions with this fix in the next week or so.
