### ISSUE TITLE
Client side validations of rjsf generated forms

### ISSUE THREAD

**Issue by mishaschwartz** [MarkUsProject/Markus#5444]
With rjsf v3.0 (#5437), defaults are finally handled properly which means that we can finally do client side form validations that won't be confusing to the user. 

However, the default way that rjsf displays validation errors is pretty ugly so we should customize it: https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/

**Comment by david-yz-liu** [comment]
Closed in #6568
