### ISSUE TITLE
Submissions view doesn't show repo name

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#5497]
After I created all the groups, I navigated to the Submissions view, and the repo name was not shown.  The student account name was given in the repo column.  

This is related to #5496 where I was suprised that repos were created with the group_xxxx name instead of the student account name.

**Comment by mishaschwartz** [comment]
The "Repository" column on the submissions table displays the group name, not the basename of the group's repository. 
This is the expected behaviour so I think this is not a bug.
