### ISSUE TITLE
don't request admin password when switching role

### ISSUE THREAD

**Issue by hhc97** [MarkUsProject/Markus#5502]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/46637781/133952511-506403a8-9800-48b2-945e-736c6e313bf9.png">
Why is it that when an admin tries to change roles, the admin password is also needed? The user who is changing roles is already authenticated as an admin, so why the extra check here?  

I raise this issue because my web browser keeps asking if I want to save this new username and password combination, because it think's I've just logged in with new credentials, which is really not the case.

Could the need for an admin password be removed from the change role interface?

On that note, a dropdown that suggests the potential matches for the user to switch to would be useful here, but not strictly necessary.

**Comment by david-yz-liu** [comment]
Thanks for making this issue. We removed the "Admin password" input in #5685.
