### ISSUE TITLE
Updating Docker Wiki Page

### ISSUE THREAD

**Issue by MShwed** [MarkUsProject/Markus#5554]
After following the instructions for setting up Markus following the intstructions here: https://github.com/MarkUsProject/Markus/wiki/Developer-Guide--Set-Up-With-Docker#setting-up-the-autotester-draft

I found that in the `Setting up the autotester` section the suggested URL for mac to follow is: `host.docker.internal:3000/csc108`.

Running:
- Docker Desktop 4.0.1
- Docker Engine 20.10.8 
- Compose 1.29.2
- Big Sur 11.6

Resulted in the suggested URL `host.docker.internal:3000/csc108` not being resolved.

Alternatively the URL: `docker.for.mac.localhost:3000/csc108` resolves appropriately.

It might be beneficial to update the Wiki to reflect this. 

cc @david-yz-liu

**Comment by pretendWhale** [comment]
Closing as this report references the deprecated MarkUs wiki. This is addressed in the[ current wiki autotester setup instructions](https://github.com/MarkUsProject/Wiki/blob/master/Developer-Guide--Set-Up-With-Docker.md).
