### ISSUE TITLE
Bug Report: Display name not used for grace token deductions

### ISSUE THREAD

**Issue by dakotamcinnis** [MarkUsProject/Markus#5610]
**Related Feature:** #4876 

**Reason for change:** People's official first name + last name are accidentally being shown to their group members.

**Current Behaviour:** 

GIVEN a user has a display name that is different from their first name and last name
AND they have a group for an assignment
AND the group submits the assignment after the due date, using some grace tokens
WHEN the assignment results are back
THEN their official first + last name are shown next to grace token deductions

**Expected Behaviour:**

GIVEN \<see above \>
WHEN \<see above \>
THEN _their display name_ is shown next to grace token deductions

----

**Where's the fix needed?:**
- In the summary panel of an assignment result
- See [app/assets/javascripts/Components/Result/summary_panel.jsx#L258](https://github.com/MarkUsProject/Markus/blob/master/app/assets/javascripts/Components/Result/summary_panel.jsx#L258)

**Comment by david-yz-liu** [comment]
Thank you for reporting this, @dakotamcinnis!
