### ISSUE TITLE
Visibility problem:  Default hidden does not allow section visible

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#5740]
I created an assignment and I thought I would take advantage of the new ability to hide an assignment by section.

Here is what I did
1. Added my 0test student to a section called "test"
2. Checked Enable section-specific settings 
3. Set "Hide assignment from students" to "Hidden
4. Set the "Hidden" column for section "test" to "Visible"
5. Switch role to 0test - I can't see the assignment

**Comment by pretendWhale** [comment]
Thanks for the report! The student update form was bugged, so even though MarkUs reported the student being added to the new "test" section, the student was not actually added to the section correctly. Fixed by #5739 and in the current release.
