### ISSUE TITLE
switch role leads to 403

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#5741]
I was able to switch role to a student and then back again

As a student, I made the mistake of navigating to a page that I did not have permissions to as a student using the back button.  Now every page on MarkUs gives me a 403 even the main page: https://markus.teach.cs.toronto.edu/2022-01/courses.  

The only way I can figure out to get out of this is to delete the cookie.

**Comment by mishaschwartz** [comment]
I was unable to recreate this issue locally or on one of the current MarkUs instance running version 2.0.2.

I do note though that when you have switched roles the `/courses` route _should_ give a 403 error (you have permission to see what the student sees only for the current course, not for any course the student might be enrolled in).

Is it possible that you just got stuck where every route you could go back to was an instructor only route? For example, if you try this and go to the `/courses/1/assignments` path (when switched to the student) does that work? That path should be visible to both instructors and students.

**Comment by reidka** [comment]
Yes, I can get to /courses/1/assignments, but then I have to know that CSC209 has course id 1.

It used to be that I could go back to the login page and login again, but that doesn't work in this model.  Maybe a 403 could redirect somewhere?
