### ISSUE TITLE
Enable hiding graders and instructors

### ISSUE THREAD

**Issue by mishaschwartz** [MarkUsProject/Markus#5826]
Currently we support hiding student roles, this does not delete them from the database but hides them from the UI and sets various policies so that the student can't interact with the course. 

We should also support the ability to hide graders and instructors users:

- no database changes needed because the `hidden` column already exists on the roles table
- change grader and instructor views to enable setting the hidden value through the UI
- update policies so that hidden roles cannot interact with the given course

**Comment by anoverga17** [comment]
Will update as I test more but upon analyzing the code, it looks like the only real difference between a hidden student and a normal student are that hidden students:

1. Cannot see the course automatically through dashboard (need to manually enter course link)
2. Cannot be added to a new group (cloned or fresh)
3. They are not included in the grade entry form CSV when graders download it 
4. Their data is not included in the grade entry form summary stats (they are included for the assignment summary stats)

In all other aspects hidden and normal students are the same

**Comment by mishaschwartz** [comment]
Thanks @anoverga17 for that summary. Here is what I'm thinking for all users:

- keep all the things you listed above in place (except don't allow them to access the course even with a direct link)
- hidden users cannot view the course at all (this can be implemented by adding a check for `hidden: false` in the `current_role` function)
- hidden users do not have permission to access repositories (update the check_repo_permissions function to check if a user is hidden or not)
- on the graders table (left-hand side table on the Graders tab), add a checkbox to toggle whether hidden graders are shown on that table.
- allow instructors to set whether TAs and students are hidden
- allow admins to set whether instructors are hidden

@david-yz-liu can you confirm whether that makes sense and if it's consistent with what quercus is doing as well.

**Comment by anoverga17** [comment]
Thanks @mishaschwartz that makes a lot of sense. I will get to it.
