### ISSUE TITLE
Allow results to be released through generated URLs

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#6242]
We have a use case for releasing grades to students through generated "magic URLs" rather than the web interface. I'll call these *release URLs* below. (This specific request is for allowed students to view final exam results, without releasing the results in bulk or having to manually release results for each individual request.)

The specs here are:

- When an instructor is setting up an assignment, provide a new configuration option for enabling the generation of release URLs.
- When an instructor is viewing submissions, provide a new option to "generate release URLs" in addition to the existing ("release marks").
- That option should export a CSV file containing the same student information as the other student export data tables (e.g. assignment marks summary), and an additional column with a link that the student could use to view their results.

    *Note*: the typical workflow would be for the instructor to send that CSV to a central office that manages student requests to view that assessment. When the student makes the request, that office can then give the student that URL for viewing, without the office staff requiring direct access to MarkUs.
- Each link should have the same permission setup as the normal `view_marks` route, except it doesn't check whether the result has been released or not. So if a student gets their link, they can view their result at any time.
- Each link shouldn't be brute-forceable (or computable given any information about the course/assessment/student). (e.g., using a random hash function or something)
- The URLs should be created with an expiry time relative to when the URL is created; each assessment should have a configuration option setting the URL expiration time.

Optional "nice to have" features/things to discuss:

- *Possible feature*: Allow instructors to view/manage these URLs in the web interface
- *Possible feature*: Allow instructors to manually expire URLs (e.g., by selecting specific rows in the submissions table)
- *Consideration*: If an instructor generates release URLs twice for the same submission, what is the expected behaviour? Possibilities:
    - Old link expired, new link generated
    - Old link returned, same expiry date
    - Old link returned, new expiry date (i.e., the configured "time to expiry" + the time when the link was re-generated)
- *Consideration*: How does this interact with results being "current" or not? If an instructor recollects a submission, does a generated release URL for an older result remain or become expired?

**Comment by mishaschwartz** [comment]
Thoughts and questions:

- does this feature also need to be per-section? Is there a use case where one section can view released results normally and another only via the URLs?
