### ISSUE TITLE
Allow bulk collection of most recent submission

### ISSUE THREAD

**Issue by mishaschwartz** [MarkUsProject/Markus#6253]
When bulk collecting submissions, MarkUs collects the last revision from before the collection time. We should also provide the option to bulk collect the most recent revision (regardless of the collection time). 

When using this option, the instructor should also be able to choose whether or not to apply penalties (if any)

This will likely interact with the feature suggested in #6252

**Comment by david-yz-liu** [comment]
Closed in #6341
