### ISSUE TITLE
Add additional bulk collection options

### ISSUE THREAD

**Issue by mishaschwartz** [MarkUsProject/Markus#6254]
When collecting bulk submissions, we should provide the following options:

- collect all selected (already implemented)
- collect all selected that does not have a previously collected submission (already implemented)
- collect all selected that does not have a previously collected submission OR has a newer revision
    - also provide the option to select whether penalties apply (if the new revision collected is during the penalty period)
    - also provide the option to select whether to collect a revision selected after the collection date (see #6252 and #6253)

**Comment by pretendWhale** [comment]
Closed via #6341
