### ISSUE TITLE
Bug: Automated Tests Hanging

### ISSUE THREAD

**Issue by dakotamcinnis** [MarkUsProject/Markus#6286]
**Overview:** Today, the first test in our automated test suite (named "init") does not complete. Our test suite's run still says "In Progress" after multiple hours. As of 5:10pm, I am seeing the following...

<img width="1586" alt="Screen Shot 2022-10-17 at 4 51 21 PM" src="https://user-images.githubusercontent.com/54950797/196283965-37119d03-721a-41cd-84df-1d2e0b43bd0f.png">

**User & Project Information:**
- UTorID: mcinni21
- Course: CSC458
- Assignment: PA1
- Group?: Yes. Size 3.
- Page where I view automated tests: https://markus.teach.cs.toronto.edu/2022-09/courses/24/assignments/57/automated_tests/student_interface

**Usual Behaviour:** When we were running tests over this weekend, we had tests running efficiently (i.e.: finishing within a matter of minutes). For instance, here is a test run from Saturday. Specifically, I have highlighted how long the first test called "init" takes:

_The entire test suite's data_

<img width="564" alt="Screen Shot 2022-10-17 at 5 02 16 PM" src="https://user-images.githubusercontent.com/54950797/196283481-703d0995-321f-4c39-a8ce-340ed6ea5a3e.png">

_The first test's runtime_

<img width="1654" alt="Screen Shot 2022-10-17 at 5 05 25 PM" src="https://user-images.githubusercontent.com/54950797/196283610-4d8f9086-85f4-4588-9c82-221f429945d2.png">

**Problem:** Today, we have not had tests running efficiently (i.e.: waiting multiple hours and even starting a new test run, with no results provided). Specifically, I would like to show that our first test called "init" has not completed:

<img width="1355" alt="Screen Shot 2022-10-17 at 5 11 51 PM" src="https://user-images.githubusercontent.com/54950797/196284556-3263e1d5-d132-4091-88c9-660701f2dd64.png">

**Comment by FaridZandi** [comment]
This is the TA monitoring the testing system. 

I can see that the submission from 15:24:07 was tested normally with proper output, and the job was ready by 15:24:54. The test ID is 316 and the job is handled by the test-runner 4. 

However, the result is not sent back to the Markus backend or is lost somewhere in the process.

**Comment by dakotamcinnis** [comment]
@david-yz-liu @mishaschwartz When this bug was in, I had a couple of runs that remained "in progess". Do you expect this to be fixed after this PR?

Currently, I still see them as "in progress"

<img width="1586" alt="Screen Shot 2022-10-18 at 1 18 46 PM" src="https://user-images.githubusercontent.com/54950797/196500588-96b230fc-a9b0-49b1-92ba-b4a29e0267ff.png">

I'm also creating a new test run right now, to see if it's resolved.

**Comment by dakotamcinnis** [comment]
Am I testing before the PR has even been deployed?

**Comment by mishaschwartz** [comment]
@dakotamcinnis @FaridZandi 

The new release has been made and the version of MarkUs that your instance is running should now be updated. Test results from now on should be shown as normal when run by either a student, TA, or instructor. 

I'm going to close this ticket but feel free to comment and re-open if you have further questions
