### ISSUE TITLE
Graders: Tracking Marking Completion/Remaining

### ISSUE THREAD

**Issue by MichaelLiut** [MarkUsProject/Markus#6304]
It would be ideal for graders, who are randomly assigned a subset of submission to mark to be able to see how many submissions they have left to grade, but also how many they have completed. 

As marking is often distributed by questions (indicated using different criteria), having a way to assign a grader to a specific criteria (on top of subsets of submissions) and then allow them to see their progress, would be ideal. 

Additionally, it would be beneficial for admins (instructors) to be able to view the progress of individual markers. Allowing us to see how many submissions (in their subset) they've completed grading for.

**Comment by mishaschwartz** [comment]
Hi @MichaelLiut, 

I'm pretty sure most of these features are already present in MarkUs. Please let me know if I'm missing anything:

- [See how many submissions graders have left/have completed](https://github.com/MarkUsProject/Wiki/blob/v2.1.5/Instructor-Guide--Assignments--Marking--Grading-View.md#grading-bar)
- [Assign graders to criteria](https://github.com/MarkUsProject/Wiki/blob/v2.1.5/Instructor-Guide--Assignments--Assigning-Graders.md#assign-to-criteria)
- [Viewing the progress of individual graders](https://github.com/MarkUsProject/Wiki/blob/53993d74413b711d259c1711049e91dcb3bddbf9/Instructor-Guide--Assignments--Summary.md#grader-distribution)
