### ISSUE TITLE
Preview student view?

### ISSUE THREAD

**Issue by alecjacobson** [MarkUsProject/Markus#6361]
Is there a way from my instructor account to preview what the students see for an assignment?

(For example, I am trying to collect URLs but I don't know how this appears to students)

**Comment by mishaschwartz** [comment]
Hi @alecjacobson, please see the "Switch Role" option in the dropdown menu at the top right of the screen.
There is also a (slightly out of date) wiki page [here](https://github.com/MarkUsProject/Wiki/blob/master/Instructor-Guide--Student-View.md) with more information.
