### ISSUE TITLE
Allow negative bonus marks in Marks Spreadsheets

### ISSUE THREAD

**Issue by mishaschwartz** [MarkUsProject/Markus#6383]
Assignments currently support positive or negative bonus marks, Marks Spreadsheets (grade entry forms) should also be able support both.

Some things to think about:

- what should the minimum value be? (set by the user in the form? negative value of the total for that column? unlimited?)
- should we extend this to regular (non-bonus) columns as well?

**Comment by david-yz-liu** [comment]
For now, we will just allow negative marks for bonus columns, with no lower limit. However, for the *total mark* we'll cap that at 0 (so the total mark can't be negative). This is consistent with what we do with assignment marks (only "extra marks" can be negative; result total mark can't be below 0).
