### ISSUE TITLE
Allow deletion of roles and users

### ISSUE THREAD

**Issue by mishaschwartz** [MarkUsProject/Markus#6421]
- Student and TA roles should be deletable by admins and instructors
- Instructor roles should be deletable by admins
- EndUser users should be deletable by admins

Things to consider:

When a role or user is deleted, do we cascade that deletion to all associated records, or do we allow those records to remain with a null association to the user/role. We may want to enable this on a case by case basis. 
For example, deleting a user should probably delete any associated roles because a role without a user doesn't make a lot of sense. But deleting a Ta shouldn't necessarily delete marks assigned by that TA.

**Comment by david-yz-liu** [comment]
Duplicate of #5827
