### ISSUE TITLE
Syntax highlighting: very faint font colour for C preprocessor lines

### ISSUE THREAD

**Issue by AlexeyKhrabrov** [MarkUsProject/Markus#6484]
See attached screenshot. The text looks very faint to me on a few different displays I've tried and across different browsers.

![Screenshot 2023-02-24 at 12-20-40 MarkUs - Edit](https://user-images.githubusercontent.com/9388553/221245792-bbe6757c-529c-4d00-aa44-f67307a079d8.png)

**Comment by david-yz-liu** [comment]
Thank for reporting this, @AlexeyKhrabrov!
