### ISSUE TITLE
Syntax highlighting: incorrectly parsed /**/ comments after // comments in C code

### ISSUE THREAD

**Issue by AlexeyKhrabrov** [MarkUsProject/Markus#6485]
See attached screenshot.

![Screenshot 2023-02-24 at 12-27-30 MarkUs - Edit](https://user-images.githubusercontent.com/9388553/221247435-0aa22a53-89aa-4baf-924a-75668f54f50f.png)

**Comment by david-yz-liu** [comment]
Thanks @AlexeyKhrabrov, I took a look at this one and it's going to be a bit more annoying to fix. Might wait until #6140.
