### ISSUE TITLE
Add ability to create/update/delete extensions through the API

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#6713]
Steps to implement:

- implement API
  - Server component
  - Client component (python)
- implement Unit Tests

**Comment by donny-wong** [comment]
The code implementation is complete. Now I am implementing the unit tests

**Comment by donny-wong** [comment]
PR has been created. Next step is to work on the client utility library which is in Python.

**Comment by donny-wong** [comment]
updated changes following PR request. Need to add instructions for this feature on MarkUs wiki.

**Comment by david-yz-liu** [comment]
Closed in #6743 (but still need to update Wiki).
