### ISSUE TITLE
TestRunTable not updated after running tests AB#47

### ISSUE THREAD

**Issue by DanielDervishi** [MarkUsProject/Markus#6751]
When I run tests against my submission for a course, the table which displays test results isn't automatically updated upon completion. 

It seems the initial handshake when establishing the web socket connection is failing due to the user being "unauthorized" (see images)

Request made in the frontend:
<img width="454" alt="Screenshot 2023-09-26 at 10 59 51 PM" src="https://github.com/MarkUsProject/Markus/assets/58835213/3255dcf0-12a5-49b1-ace5-dafa2a037988">

Messages associated with the response from the server:
<img width="389" alt="Screenshot 2023-09-26 at 10 58 16 PM" src="https://github.com/MarkUsProject/Markus/assets/58835213/1b771c70-8115-4660-9095-fe89840d812d">

**Comment by pretendWhale** [comment]
Closed via #6912
