### ISSUE TITLE
Deleting of a group's repository by the inviter should only be possible if the repository is empty

### ISSUE THREAD

**Issue by divarvel** [MarkUsProject/Markus#69]
This could become a problem, if the instructor uses the new feature of allowing/disallowing Web-submits for some, but not all assignments AND allows students to form groups on their own:

Scenario:

   1. Setup an assignment and disallow web-submits
   2. Allow students to form groups (from 1 to >=1 people)
   3. Now, students can't submit via Markus' web interface, but that's (submitting via web interface) the only way we set if a grouping has a submission or not. Then, it would happily allow deletion of the repository, although there might have happened some svn command-line commits to the repo.

We need to implement functionality to check if the repository is effectively empty (all files are deleted in the latest revision).

Currently, instructors should not allow students to form their own group when they setup the assignment in a way so that web-submits aren't allowed.

**Comment by david-yz-liu** [comment]
We don't think this is an issue.
