### ISSUE TITLE
"Release Marks" and "Unrelease Marks" buttons should be disabled appropriately

### ISSUE THREAD

**Issue by tobioboye** [MarkUsProject/Markus#730]
The Release Marks button should only be enabled when the admin has selected group(s) whom the grading of their assignments have been completed and the Unrelease marks button should be enabled only when the admin has selected some group(s) whose assignment marks were released earlier. Tooltips can also be displayed to indicate the circumstances under which each of the buttons will be enabled to improve usability.

To view the buttons
1 Login as Admin
2 Navigate to the Assignments tab -> Submissions

**Comment by david-yz-liu** [comment]
@Eitredes This is not a remark request feature, but is closely related, and may be worth looking into.

**Comment by david-yz-liu** [comment]
@Eitredes This is still open for you.

**Comment by david-yz-liu** [comment]
Done in #2557
