### ISSUE TITLE
UI Rework: Menu bar

### ISSUE THREAD

**Issue by hoboman313** [MarkUsProject/Markus#731]
The scenario:
An admin user wants to modify the marking scheme for an assignment. With our current menu bar, the user would have to:
1.) click on "Assignments"
2.) select an assignment
3.) select "Marking Scheme" from the sub-sub-menu
For a grand total of three http requests.

The problem:
The user is forced to make three http requests, which is a waste of user's time and is unnecessary work for the server. In addition, with each additional request, we keep displaying more and more menu bars ( 3 lines of menus at step #3 ) which limits the actual "work" area.

The solution:
Substitute the current menu with a dropdown menu. This menu should be partly dynamic, as the "Assignments" dropdown will have to be dynamically filled with available assignments and their associated links.

The end result should look similar in style to the following example: http://css3menu.com/simple-css3-pull-down-menu.html

Take note of the triangles/arrows that are a part of some of the menu items as they're used to signify that the item may be expanded. It is preferable to use icons + text for menu items although that is definitely up for debate. In general, icons tend to speed up the menu use for advanced users who tend to just glance over the choices, while the text is for beginner users who must carefully read each possible menu option.

**Comment by david-yz-liu** [comment]
See #1961
