### ISSUE TITLE
Submissions Table should have sortable column for assigned Graders

### ISSUE THREAD

**Issue by benjaminvialle** [MarkUsProject/Markus#75]
From Byron:

"I'd like to have the grader listed on the submissions list, ideally in a sortable column, so I can easily check the grading of an individual grader." 

Modified by c8braver 2 months ago:

how would we deal with multiple graders assigned to a single group? this will be a common occurrence with the new ability to assign graders to criteria.

**Comment by david-yz-liu** [comment]
Work in #2151 is fine for now.
