### ISSUE TITLE
RubricCriterion throws rather unspecific RuntimeErrors when dealing with CSV uploads

### ISSUE THREAD

**Issue by divarvel** [MarkUsProject/Markus#83]
When an instructor uploads a rubric CSV file, anytime something goes wrong (the weight is missing, or an invalid type, etc), a RuntimeError Exception is raised. These could be more specific...perhaps a TypeError in this particular instance.

It's not too big of a deal right now - just details.

**Comment by Skololo** [comment]
Good Lord, this is old. Whatever. Dibs on fixing this one or dying valiantly in the effort.

**Comment by david-yz-liu** [comment]
@paymog If I remember correctly, you worked on a related issue at the code sprint. I think this is up your alley.

**Comment by paymog** [comment]
All over it (once the weekend rolls around).

**Comment by paymog** [comment]
Just to be clear, what's shown in the second screenshot is the problem, correct?

**Comment by david-yz-liu** [comment]
Yes, that's right.
