### ISSUE TITLE
Feature request: Ability to partition submissions.

### ISSUE THREAD

**Issue by fpitt** [MarkUsProject/Markus#886]
Something like this has been requested by a few of my TAs over the years.  They would like to be able to quickly partition the submissions into a number of "categories", for example, doing a rough first pass through the submissions to split them into "good/mediocre/poor".  Then they can go back and grade each submission more thoroughly.

The interface should allow for these "categories" to be defined for each assignment, and to be editable by the markers (like the annotations), as well as having one more drop-down menu (or some other easy mechanism) to indicate the assignment's current "category" and allow for it to be quickly changed.

**Comment by david-yz-liu** [comment]
Implemented a tagging feature in #1947.
