### ISSUE TITLE
(Assignment without group => Graders) displays both group name and user name, even if they're the same

### ISSUE THREAD

**Issue by e-morency** [MarkUsProject/Markus#900]
When managing graders for an assignment without groups, the group name corresponds to a single student's username.  At the moment, both are displayed. In this case (when grouping is disabled for an assignment), only the group name should be displayed.

**Comment by david-yz-liu** [comment]
@Eitredes please also check this in the submissions table, and in the grading view (results).

**Comment by Eitredes** [comment]
@david-yz-liu  The current version of the table for groups on the screen for managing graders does not display members of the group even if there are multiple members for the group. Would you prefer that behaviour, or list members if there are multiple members/the group name doesn't match the only member's name?

**Comment by david-yz-liu** [comment]
@Eitredes No, that's fine. You can just work on the submissions table and related places, then.
