### ISSUE TITLE
Complete TODO tests inside SubmissionControllerTest

### ISSUE THREAD

**Issue by divarvel** [MarkUsProject/Markus#92]
There are a bunch of left over TODOs inside the SubmissionControllerTest

    * TODO Figure out how to remove fixture_file_upload
    * TODO figure out how to test this test into the one above
    * TODO Figure out how to remove fixture_file_upload
    * TODO: Test that a student can't replace file if out of sync
    * TODO: Test that a student can't replace a file if the new file has a different name
    * TODO: TEST REPO BROWSER HERE
    * TODO:
    * Test whether or not an Instructor can release/unrelease results correctly
    * Test whether or not an Instructor can download files from student repos

**Comment by MatakuT** [comment]
Is there still a need to remove fixture_file_upload calls? Why is leaking memory such a big issue if the test suite just rans once and the code terminates?
