### ISSUE TITLE
Allow annotating part of a line

### ISSUE THREAD

**Issue by yc2lee** [MarkUsProject/Markus#989]
I think it would be nice if you could annotate just part of a line, instead of the entire line. Markers will be able to tell students more precisely where they made mistakes.

For example, if students have to write a long Bash command, you'd be able to  just highlight the part that's wrong. For example:

    cat pcat | egrep 'put' | wc -l | diff correct_count -  # student's code
    |--------------------|
    highlight just this part of the line and annotate with "use egrep 'put' pcat"

**Comment by spring-ryanc** [comment]
@david-yz-liu I have a rough implementation of this now, but it has presented a few issues. It will require a bit more work to allow multiple annotations on the same line and the unglow method might need some work.

Im just wondering if its okay that I work on this next week as well or should I get started on the other issues I was assigned?

**Comment by david-yz-liu** [comment]
@spring-ryanc I'd like to see the work you've done so far. I've created a new branch off of the main repo called line-annotations; please make a pull request into that branch and wait for feedback.

In the mean time, working on #1850 and #1981 should be a nice break for you.
